// Code generated by ent, DO NOT EDIT.

package usersession

import (
	"ikik-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// Sid applies equality check predicate on the "sid" field. It's identical to SidEQ.
func Sid(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldSid, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUserID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldVersion, v))
}

// UserAuthVersion applies equality check predicate on the "user_auth_version" field. It's identical to UserAuthVersionEQ.
func UserAuthVersion(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUserAuthVersion, v))
}

// RefreshHash applies equality check predicate on the "refresh_hash" field. It's identical to RefreshHashEQ.
func RefreshHash(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldRefreshHash, v))
}

// PreviousRefreshHash applies equality check predicate on the "previous_refresh_hash" field. It's identical to PreviousRefreshHashEQ.
func PreviousRefreshHash(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldPreviousRefreshHash, v))
}

// PreviousValidUntil applies equality check predicate on the "previous_valid_until" field. It's identical to PreviousValidUntilEQ.
func PreviousValidUntil(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldPreviousValidUntil, v))
}

// LoginMethod applies equality check predicate on the "login_method" field. It's identical to LoginMethodEQ.
func LoginMethod(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldLoginMethod, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUserAgent, v))
}

// LastActiveAt applies equality check predicate on the "last_active_at" field. It's identical to LastActiveAtEQ.
func LastActiveAt(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldLastActiveAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedReason applies equality check predicate on the "revoked_reason" field. It's identical to RevokedReasonEQ.
func RevokedReason(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldRevokedReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// SidEQ applies the EQ predicate on the "sid" field.
func SidEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldSid, v))
}

// SidNEQ applies the NEQ predicate on the "sid" field.
func SidNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldSid, v))
}

// SidIn applies the In predicate on the "sid" field.
func SidIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldSid, vs...))
}

// SidNotIn applies the NotIn predicate on the "sid" field.
func SidNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldSid, vs...))
}

// SidGT applies the GT predicate on the "sid" field.
func SidGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldSid, v))
}

// SidGTE applies the GTE predicate on the "sid" field.
func SidGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldSid, v))
}

// SidLT applies the LT predicate on the "sid" field.
func SidLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldSid, v))
}

// SidLTE applies the LTE predicate on the "sid" field.
func SidLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldSid, v))
}

// SidContains applies the Contains predicate on the "sid" field.
func SidContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldSid, v))
}

// SidHasPrefix applies the HasPrefix predicate on the "sid" field.
func SidHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldSid, v))
}

// SidHasSuffix applies the HasSuffix predicate on the "sid" field.
func SidHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldSid, v))
}

// SidEqualFold applies the EqualFold predicate on the "sid" field.
func SidEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldSid, v))
}

// SidContainsFold applies the ContainsFold predicate on the "sid" field.
func SidContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldSid, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldUserID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldVersion, v))
}

// UserAuthVersionEQ applies the EQ predicate on the "user_auth_version" field.
func UserAuthVersionEQ(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUserAuthVersion, v))
}

// UserAuthVersionNEQ applies the NEQ predicate on the "user_auth_version" field.
func UserAuthVersionNEQ(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldUserAuthVersion, v))
}

// UserAuthVersionIn applies the In predicate on the "user_auth_version" field.
func UserAuthVersionIn(vs ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldUserAuthVersion, vs...))
}

// UserAuthVersionNotIn applies the NotIn predicate on the "user_auth_version" field.
func UserAuthVersionNotIn(vs ...int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldUserAuthVersion, vs...))
}

// UserAuthVersionGT applies the GT predicate on the "user_auth_version" field.
func UserAuthVersionGT(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldUserAuthVersion, v))
}

// UserAuthVersionGTE applies the GTE predicate on the "user_auth_version" field.
func UserAuthVersionGTE(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldUserAuthVersion, v))
}

// UserAuthVersionLT applies the LT predicate on the "user_auth_version" field.
func UserAuthVersionLT(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldUserAuthVersion, v))
}

// UserAuthVersionLTE applies the LTE predicate on the "user_auth_version" field.
func UserAuthVersionLTE(v int64) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldUserAuthVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldStatus, vs...))
}

// RefreshHashEQ applies the EQ predicate on the "refresh_hash" field.
func RefreshHashEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldRefreshHash, v))
}

// RefreshHashNEQ applies the NEQ predicate on the "refresh_hash" field.
func RefreshHashNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldRefreshHash, v))
}

// RefreshHashIn applies the In predicate on the "refresh_hash" field.
func RefreshHashIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldRefreshHash, vs...))
}

// RefreshHashNotIn applies the NotIn predicate on the "refresh_hash" field.
func RefreshHashNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldRefreshHash, vs...))
}

// RefreshHashGT applies the GT predicate on the "refresh_hash" field.
func RefreshHashGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldRefreshHash, v))
}

// RefreshHashGTE applies the GTE predicate on the "refresh_hash" field.
func RefreshHashGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldRefreshHash, v))
}

// RefreshHashLT applies the LT predicate on the "refresh_hash" field.
func RefreshHashLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldRefreshHash, v))
}

// RefreshHashLTE applies the LTE predicate on the "refresh_hash" field.
func RefreshHashLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldRefreshHash, v))
}

// RefreshHashContains applies the Contains predicate on the "refresh_hash" field.
func RefreshHashContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldRefreshHash, v))
}

// RefreshHashHasPrefix applies the HasPrefix predicate on the "refresh_hash" field.
func RefreshHashHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldRefreshHash, v))
}

// RefreshHashHasSuffix applies the HasSuffix predicate on the "refresh_hash" field.
func RefreshHashHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldRefreshHash, v))
}

// RefreshHashEqualFold applies the EqualFold predicate on the "refresh_hash" field.
func RefreshHashEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldRefreshHash, v))
}

// RefreshHashContainsFold applies the ContainsFold predicate on the "refresh_hash" field.
func RefreshHashContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldRefreshHash, v))
}

// PreviousRefreshHashEQ applies the EQ predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashNEQ applies the NEQ predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashIn applies the In predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldPreviousRefreshHash, vs...))
}

// PreviousRefreshHashNotIn applies the NotIn predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldPreviousRefreshHash, vs...))
}

// PreviousRefreshHashGT applies the GT predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashGTE applies the GTE predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashLT applies the LT predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashLTE applies the LTE predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashContains applies the Contains predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashHasPrefix applies the HasPrefix predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashHasSuffix applies the HasSuffix predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashEqualFold applies the EqualFold predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldPreviousRefreshHash, v))
}

// PreviousRefreshHashContainsFold applies the ContainsFold predicate on the "previous_refresh_hash" field.
func PreviousRefreshHashContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldPreviousRefreshHash, v))
}

// PreviousValidUntilEQ applies the EQ predicate on the "previous_valid_until" field.
func PreviousValidUntilEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldPreviousValidUntil, v))
}

// PreviousValidUntilNEQ applies the NEQ predicate on the "previous_valid_until" field.
func PreviousValidUntilNEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldPreviousValidUntil, v))
}

// PreviousValidUntilIn applies the In predicate on the "previous_valid_until" field.
func PreviousValidUntilIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldPreviousValidUntil, vs...))
}

// PreviousValidUntilNotIn applies the NotIn predicate on the "previous_valid_until" field.
func PreviousValidUntilNotIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldPreviousValidUntil, vs...))
}

// PreviousValidUntilGT applies the GT predicate on the "previous_valid_until" field.
func PreviousValidUntilGT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldPreviousValidUntil, v))
}

// PreviousValidUntilGTE applies the GTE predicate on the "previous_valid_until" field.
func PreviousValidUntilGTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldPreviousValidUntil, v))
}

// PreviousValidUntilLT applies the LT predicate on the "previous_valid_until" field.
func PreviousValidUntilLT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldPreviousValidUntil, v))
}

// PreviousValidUntilLTE applies the LTE predicate on the "previous_valid_until" field.
func PreviousValidUntilLTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldPreviousValidUntil, v))
}

// PreviousValidUntilIsNil applies the IsNil predicate on the "previous_valid_until" field.
func PreviousValidUntilIsNil() predicate.UserSession {
	return predicate.UserSession(sql.FieldIsNull(FieldPreviousValidUntil))
}

// PreviousValidUntilNotNil applies the NotNil predicate on the "previous_valid_until" field.
func PreviousValidUntilNotNil() predicate.UserSession {
	return predicate.UserSession(sql.FieldNotNull(FieldPreviousValidUntil))
}

// LoginMethodEQ applies the EQ predicate on the "login_method" field.
func LoginMethodEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldLoginMethod, v))
}

// LoginMethodNEQ applies the NEQ predicate on the "login_method" field.
func LoginMethodNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldLoginMethod, v))
}

// LoginMethodIn applies the In predicate on the "login_method" field.
func LoginMethodIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldLoginMethod, vs...))
}

// LoginMethodNotIn applies the NotIn predicate on the "login_method" field.
func LoginMethodNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldLoginMethod, vs...))
}

// LoginMethodGT applies the GT predicate on the "login_method" field.
func LoginMethodGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldLoginMethod, v))
}

// LoginMethodGTE applies the GTE predicate on the "login_method" field.
func LoginMethodGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldLoginMethod, v))
}

// LoginMethodLT applies the LT predicate on the "login_method" field.
func LoginMethodLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldLoginMethod, v))
}

// LoginMethodLTE applies the LTE predicate on the "login_method" field.
func LoginMethodLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldLoginMethod, v))
}

// LoginMethodContains applies the Contains predicate on the "login_method" field.
func LoginMethodContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldLoginMethod, v))
}

// LoginMethodHasPrefix applies the HasPrefix predicate on the "login_method" field.
func LoginMethodHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldLoginMethod, v))
}

// LoginMethodHasSuffix applies the HasSuffix predicate on the "login_method" field.
func LoginMethodHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldLoginMethod, v))
}

// LoginMethodEqualFold applies the EqualFold predicate on the "login_method" field.
func LoginMethodEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldLoginMethod, v))
}

// LoginMethodContainsFold applies the ContainsFold predicate on the "login_method" field.
func LoginMethodContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldLoginMethod, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldUserAgent, v))
}

// LastActiveAtEQ applies the EQ predicate on the "last_active_at" field.
func LastActiveAtEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldLastActiveAt, v))
}

// LastActiveAtNEQ applies the NEQ predicate on the "last_active_at" field.
func LastActiveAtNEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldLastActiveAt, v))
}

// LastActiveAtIn applies the In predicate on the "last_active_at" field.
func LastActiveAtIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldLastActiveAt, vs...))
}

// LastActiveAtNotIn applies the NotIn predicate on the "last_active_at" field.
func LastActiveAtNotIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldLastActiveAt, vs...))
}

// LastActiveAtGT applies the GT predicate on the "last_active_at" field.
func LastActiveAtGT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldLastActiveAt, v))
}

// LastActiveAtGTE applies the GTE predicate on the "last_active_at" field.
func LastActiveAtGTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldLastActiveAt, v))
}

// LastActiveAtLT applies the LT predicate on the "last_active_at" field.
func LastActiveAtLT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldLastActiveAt, v))
}

// LastActiveAtLTE applies the LTE predicate on the "last_active_at" field.
func LastActiveAtLTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldLastActiveAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.UserSession {
	return predicate.UserSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.UserSession {
	return predicate.UserSession(sql.FieldNotNull(FieldRevokedAt))
}

// RevokedReasonEQ applies the EQ predicate on the "revoked_reason" field.
func RevokedReasonEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEQ(FieldRevokedReason, v))
}

// RevokedReasonNEQ applies the NEQ predicate on the "revoked_reason" field.
func RevokedReasonNEQ(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNEQ(FieldRevokedReason, v))
}

// RevokedReasonIn applies the In predicate on the "revoked_reason" field.
func RevokedReasonIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldIn(FieldRevokedReason, vs...))
}

// RevokedReasonNotIn applies the NotIn predicate on the "revoked_reason" field.
func RevokedReasonNotIn(vs ...string) predicate.UserSession {
	return predicate.UserSession(sql.FieldNotIn(FieldRevokedReason, vs...))
}

// RevokedReasonGT applies the GT predicate on the "revoked_reason" field.
func RevokedReasonGT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGT(FieldRevokedReason, v))
}

// RevokedReasonGTE applies the GTE predicate on the "revoked_reason" field.
func RevokedReasonGTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldGTE(FieldRevokedReason, v))
}

// RevokedReasonLT applies the LT predicate on the "revoked_reason" field.
func RevokedReasonLT(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLT(FieldRevokedReason, v))
}

// RevokedReasonLTE applies the LTE predicate on the "revoked_reason" field.
func RevokedReasonLTE(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldLTE(FieldRevokedReason, v))
}

// RevokedReasonContains applies the Contains predicate on the "revoked_reason" field.
func RevokedReasonContains(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContains(FieldRevokedReason, v))
}

// RevokedReasonHasPrefix applies the HasPrefix predicate on the "revoked_reason" field.
func RevokedReasonHasPrefix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasPrefix(FieldRevokedReason, v))
}

// RevokedReasonHasSuffix applies the HasSuffix predicate on the "revoked_reason" field.
func RevokedReasonHasSuffix(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldHasSuffix(FieldRevokedReason, v))
}

// RevokedReasonEqualFold applies the EqualFold predicate on the "revoked_reason" field.
func RevokedReasonEqualFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldEqualFold(FieldRevokedReason, v))
}

// RevokedReasonContainsFold applies the ContainsFold predicate on the "revoked_reason" field.
func RevokedReasonContainsFold(v string) predicate.UserSession {
	return predicate.UserSession(sql.FieldContainsFold(FieldRevokedReason, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserSession {
	return predicate.UserSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserSession {
	return predicate.UserSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSession) predicate.UserSession {
	return predicate.UserSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSession) predicate.UserSession {
	return predicate.UserSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSession) predicate.UserSession {
	return predicate.UserSession(sql.NotPredicates(p))
}
