// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/apikey"
	"ikik-api/ent/apikeygrouproute"
	"ikik-api/ent/group"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// APIKeyGroupRouteCreate is the builder for creating a APIKeyGroupRoute entity.
type APIKeyGroupRouteCreate struct {
	config
	mutation *APIKeyGroupRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyGroupRouteCreate) SetCreatedAt(v time.Time) *APIKeyGroupRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyGroupRouteCreate) SetNillableCreatedAt(v *time.Time) *APIKeyGroupRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyGroupRouteCreate) SetUpdatedAt(v time.Time) *APIKeyGroupRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyGroupRouteCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyGroupRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyGroupRouteCreate) SetAPIKeyID(v int64) *APIKeyGroupRouteCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *APIKeyGroupRouteCreate) SetGroupID(v int64) *APIKeyGroupRouteCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *APIKeyGroupRouteCreate) SetPriority(v int) *APIKeyGroupRouteCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *APIKeyGroupRouteCreate) SetNillablePriority(v *int) *APIKeyGroupRouteCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *APIKeyGroupRouteCreate) SetWeight(v int) *APIKeyGroupRouteCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *APIKeyGroupRouteCreate) SetNillableWeight(v *int) *APIKeyGroupRouteCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *APIKeyGroupRouteCreate) SetEnabled(v bool) *APIKeyGroupRouteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *APIKeyGroupRouteCreate) SetNillableEnabled(v *bool) *APIKeyGroupRouteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (_c *APIKeyGroupRouteCreate) SetCooldownSeconds(v int) *APIKeyGroupRouteCreate {
	_c.mutation.SetCooldownSeconds(v)
	return _c
}

// SetNillableCooldownSeconds sets the "cooldown_seconds" field if the given value is not nil.
func (_c *APIKeyGroupRouteCreate) SetNillableCooldownSeconds(v *int) *APIKeyGroupRouteCreate {
	if v != nil {
		_c.SetCooldownSeconds(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *APIKeyGroupRouteCreate) SetAPIKey(v *APIKey) *APIKeyGroupRouteCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *APIKeyGroupRouteCreate) SetGroup(v *Group) *APIKeyGroupRouteCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the APIKeyGroupRouteMutation object of the builder.
func (_c *APIKeyGroupRouteCreate) Mutation() *APIKeyGroupRouteMutation {
	return _c.mutation
}

// Save creates the APIKeyGroupRoute in the database.
func (_c *APIKeyGroupRouteCreate) Save(ctx context.Context) (*APIKeyGroupRoute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyGroupRouteCreate) SaveX(ctx context.Context) *APIKeyGroupRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyGroupRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyGroupRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyGroupRouteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeygrouproute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeygrouproute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := apikeygrouproute.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := apikeygrouproute.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := apikeygrouproute.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CooldownSeconds(); !ok {
		v := apikeygrouproute.DefaultCooldownSeconds
		_c.mutation.SetCooldownSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyGroupRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyGroupRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyGroupRoute.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyGroupRoute.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "APIKeyGroupRoute.group_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "APIKeyGroupRoute.priority"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "APIKeyGroupRoute.weight"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "APIKeyGroupRoute.enabled"`)}
	}
	if _, ok := _c.mutation.CooldownSeconds(); !ok {
		return &ValidationError{Name: "cooldown_seconds", err: errors.New(`ent: missing required field "APIKeyGroupRoute.cooldown_seconds"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "APIKeyGroupRoute.api_key"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "APIKeyGroupRoute.group"`)}
	}
	return nil
}

func (_c *APIKeyGroupRouteCreate) sqlSave(ctx context.Context) (*APIKeyGroupRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyGroupRouteCreate) createSpec() (*APIKeyGroupRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyGroupRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeygrouproute.Table, sqlgraph.NewFieldSpec(apikeygrouproute.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeygrouproute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeygrouproute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(apikeygrouproute.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(apikeygrouproute.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(apikeygrouproute.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CooldownSeconds(); ok {
		_spec.SetField(apikeygrouproute.FieldCooldownSeconds, field.TypeInt, value)
		_node.CooldownSeconds = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouproute.APIKeyTable,
			Columns: []string{apikeygrouproute.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeygrouproute.GroupTable,
			Columns: []string{apikeygrouproute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyGroupRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyGroupRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyGroupRouteCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyGroupRouteUpsertOne {
	_c.conflict = opts
	return &APIKeyGroupRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyGroupRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyGroupRouteCreate) OnConflictColumns(columns ...string) *APIKeyGroupRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyGroupRouteUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyGroupRouteUpsertOne is the builder for "upsert"-ing
	//  one APIKeyGroupRoute node.
	APIKeyGroupRouteUpsertOne struct {
		create *APIKeyGroupRouteCreate
	}

	// APIKeyGroupRouteUpsert is the "OnConflict" setter.
	APIKeyGroupRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupRouteUpsert) SetUpdatedAt(v time.Time) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdateUpdatedAt() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupRouteUpsert) SetAPIKeyID(v int64) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdateAPIKeyID() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupRouteUpsert) SetGroupID(v int64) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdateGroupID() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldGroupID)
	return u
}

// SetPriority sets the "priority" field.
func (u *APIKeyGroupRouteUpsert) SetPriority(v int) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdatePriority() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyGroupRouteUpsert) AddPriority(v int) *APIKeyGroupRouteUpsert {
	u.Add(apikeygrouproute.FieldPriority, v)
	return u
}

// SetWeight sets the "weight" field.
func (u *APIKeyGroupRouteUpsert) SetWeight(v int) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdateWeight() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *APIKeyGroupRouteUpsert) AddWeight(v int) *APIKeyGroupRouteUpsert {
	u.Add(apikeygrouproute.FieldWeight, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *APIKeyGroupRouteUpsert) SetEnabled(v bool) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdateEnabled() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldEnabled)
	return u
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (u *APIKeyGroupRouteUpsert) SetCooldownSeconds(v int) *APIKeyGroupRouteUpsert {
	u.Set(apikeygrouproute.FieldCooldownSeconds, v)
	return u
}

// UpdateCooldownSeconds sets the "cooldown_seconds" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsert) UpdateCooldownSeconds() *APIKeyGroupRouteUpsert {
	u.SetExcluded(apikeygrouproute.FieldCooldownSeconds)
	return u
}

// AddCooldownSeconds adds v to the "cooldown_seconds" field.
func (u *APIKeyGroupRouteUpsert) AddCooldownSeconds(v int) *APIKeyGroupRouteUpsert {
	u.Add(apikeygrouproute.FieldCooldownSeconds, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyGroupRouteUpsertOne) UpdateNewValues() *APIKeyGroupRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeygrouproute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyGroupRouteUpsertOne) Ignore() *APIKeyGroupRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyGroupRouteUpsertOne) DoNothing() *APIKeyGroupRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyGroupRouteCreate.OnConflict
// documentation for more info.
func (u *APIKeyGroupRouteUpsertOne) Update(set func(*APIKeyGroupRouteUpsert)) *APIKeyGroupRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyGroupRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupRouteUpsertOne) SetUpdatedAt(v time.Time) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdateUpdatedAt() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupRouteUpsertOne) SetAPIKeyID(v int64) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdateAPIKeyID() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupRouteUpsertOne) SetGroupID(v int64) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdateGroupID() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *APIKeyGroupRouteUpsertOne) SetPriority(v int) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyGroupRouteUpsertOne) AddPriority(v int) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdatePriority() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetWeight sets the "weight" field.
func (u *APIKeyGroupRouteUpsertOne) SetWeight(v int) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *APIKeyGroupRouteUpsertOne) AddWeight(v int) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdateWeight() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateWeight()
	})
}

// SetEnabled sets the "enabled" field.
func (u *APIKeyGroupRouteUpsertOne) SetEnabled(v bool) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdateEnabled() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateEnabled()
	})
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (u *APIKeyGroupRouteUpsertOne) SetCooldownSeconds(v int) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetCooldownSeconds(v)
	})
}

// AddCooldownSeconds adds v to the "cooldown_seconds" field.
func (u *APIKeyGroupRouteUpsertOne) AddCooldownSeconds(v int) *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.AddCooldownSeconds(v)
	})
}

// UpdateCooldownSeconds sets the "cooldown_seconds" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertOne) UpdateCooldownSeconds() *APIKeyGroupRouteUpsertOne {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateCooldownSeconds()
	})
}

// Exec executes the query.
func (u *APIKeyGroupRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyGroupRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyGroupRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyGroupRouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyGroupRouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyGroupRouteCreateBulk is the builder for creating many APIKeyGroupRoute entities in bulk.
type APIKeyGroupRouteCreateBulk struct {
	config
	err      error
	builders []*APIKeyGroupRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyGroupRoute entities in the database.
func (_c *APIKeyGroupRouteCreateBulk) Save(ctx context.Context) ([]*APIKeyGroupRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyGroupRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyGroupRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyGroupRouteCreateBulk) SaveX(ctx context.Context) []*APIKeyGroupRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyGroupRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyGroupRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyGroupRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyGroupRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyGroupRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyGroupRouteUpsertBulk {
	_c.conflict = opts
	return &APIKeyGroupRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyGroupRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyGroupRouteCreateBulk) OnConflictColumns(columns ...string) *APIKeyGroupRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyGroupRouteUpsertBulk{
		create: _c,
	}
}

// APIKeyGroupRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyGroupRoute nodes.
type APIKeyGroupRouteUpsertBulk struct {
	create *APIKeyGroupRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyGroupRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyGroupRouteUpsertBulk) UpdateNewValues() *APIKeyGroupRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeygrouproute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyGroupRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyGroupRouteUpsertBulk) Ignore() *APIKeyGroupRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyGroupRouteUpsertBulk) DoNothing() *APIKeyGroupRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyGroupRouteCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyGroupRouteUpsertBulk) Update(set func(*APIKeyGroupRouteUpsert)) *APIKeyGroupRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyGroupRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyGroupRouteUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdateUpdatedAt() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyGroupRouteUpsertBulk) SetAPIKeyID(v int64) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdateAPIKeyID() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyGroupRouteUpsertBulk) SetGroupID(v int64) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdateGroupID() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *APIKeyGroupRouteUpsertBulk) SetPriority(v int) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyGroupRouteUpsertBulk) AddPriority(v int) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdatePriority() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetWeight sets the "weight" field.
func (u *APIKeyGroupRouteUpsertBulk) SetWeight(v int) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *APIKeyGroupRouteUpsertBulk) AddWeight(v int) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdateWeight() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateWeight()
	})
}

// SetEnabled sets the "enabled" field.
func (u *APIKeyGroupRouteUpsertBulk) SetEnabled(v bool) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdateEnabled() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateEnabled()
	})
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (u *APIKeyGroupRouteUpsertBulk) SetCooldownSeconds(v int) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.SetCooldownSeconds(v)
	})
}

// AddCooldownSeconds adds v to the "cooldown_seconds" field.
func (u *APIKeyGroupRouteUpsertBulk) AddCooldownSeconds(v int) *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.AddCooldownSeconds(v)
	})
}

// UpdateCooldownSeconds sets the "cooldown_seconds" field to the value that was provided on create.
func (u *APIKeyGroupRouteUpsertBulk) UpdateCooldownSeconds() *APIKeyGroupRouteUpsertBulk {
	return u.Update(func(s *APIKeyGroupRouteUpsert) {
		s.UpdateCooldownSeconds()
	})
}

// Exec executes the query.
func (u *APIKeyGroupRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyGroupRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyGroupRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyGroupRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
