// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ikik-api/ent/developertoken"
	"ikik-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeveloperTokenDelete is the builder for deleting a DeveloperToken entity.
type DeveloperTokenDelete struct {
	config
	hooks    []Hook
	mutation *DeveloperTokenMutation
}

// Where appends a list predicates to the DeveloperTokenDelete builder.
func (_d *DeveloperTokenDelete) Where(ps ...predicate.DeveloperToken) *DeveloperTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DeveloperTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeveloperTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DeveloperTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(developertoken.Table, sqlgraph.NewFieldSpec(developertoken.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DeveloperTokenDeleteOne is the builder for deleting a single DeveloperToken entity.
type DeveloperTokenDeleteOne struct {
	_d *DeveloperTokenDelete
}

// Where appends a list predicates to the DeveloperTokenDelete builder.
func (_d *DeveloperTokenDeleteOne) Where(ps ...predicate.DeveloperToken) *DeveloperTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DeveloperTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{developertoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeveloperTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
