// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/emailbroadcast"
	"ikik-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// EmailBroadcastUpdate is the builder for updating EmailBroadcast entities.
type EmailBroadcastUpdate struct {
	config
	hooks    []Hook
	mutation *EmailBroadcastMutation
}

// Where appends a list predicates to the EmailBroadcastUpdate builder.
func (_u *EmailBroadcastUpdate) Where(ps ...predicate.EmailBroadcast) *EmailBroadcastUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EmailBroadcastUpdate) SetSubject(v string) *EmailBroadcastUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableSubject(v *string) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *EmailBroadcastUpdate) SetBody(v string) *EmailBroadcastUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableBody(v *string) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetBodyFormat sets the "body_format" field.
func (_u *EmailBroadcastUpdate) SetBodyFormat(v string) *EmailBroadcastUpdate {
	_u.mutation.SetBodyFormat(v)
	return _u
}

// SetNillableBodyFormat sets the "body_format" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableBodyFormat(v *string) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetBodyFormat(*v)
	}
	return _u
}

// SetRecipientsMode sets the "recipients_mode" field.
func (_u *EmailBroadcastUpdate) SetRecipientsMode(v string) *EmailBroadcastUpdate {
	_u.mutation.SetRecipientsMode(v)
	return _u
}

// SetNillableRecipientsMode sets the "recipients_mode" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableRecipientsMode(v *string) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetRecipientsMode(*v)
	}
	return _u
}

// SetRecipientUserIds sets the "recipient_user_ids" field.
func (_u *EmailBroadcastUpdate) SetRecipientUserIds(v []int64) *EmailBroadcastUpdate {
	_u.mutation.SetRecipientUserIds(v)
	return _u
}

// AppendRecipientUserIds appends value to the "recipient_user_ids" field.
func (_u *EmailBroadcastUpdate) AppendRecipientUserIds(v []int64) *EmailBroadcastUpdate {
	_u.mutation.AppendRecipientUserIds(v)
	return _u
}

// ClearRecipientUserIds clears the value of the "recipient_user_ids" field.
func (_u *EmailBroadcastUpdate) ClearRecipientUserIds() *EmailBroadcastUpdate {
	_u.mutation.ClearRecipientUserIds()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailBroadcastUpdate) SetStatus(v string) *EmailBroadcastUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableStatus(v *string) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *EmailBroadcastUpdate) SetTotalCount(v int) *EmailBroadcastUpdate {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableTotalCount(v *int) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *EmailBroadcastUpdate) AddTotalCount(v int) *EmailBroadcastUpdate {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *EmailBroadcastUpdate) SetSuccessCount(v int) *EmailBroadcastUpdate {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableSuccessCount(v *int) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *EmailBroadcastUpdate) AddSuccessCount(v int) *EmailBroadcastUpdate {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *EmailBroadcastUpdate) SetFailedCount(v int) *EmailBroadcastUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableFailedCount(v *int) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *EmailBroadcastUpdate) AddFailedCount(v int) *EmailBroadcastUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EmailBroadcastUpdate) SetErrorMessage(v string) *EmailBroadcastUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableErrorMessage(v *string) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *EmailBroadcastUpdate) ClearErrorMessage() *EmailBroadcastUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EmailBroadcastUpdate) SetCreatedBy(v int64) *EmailBroadcastUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableCreatedBy(v *int64) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *EmailBroadcastUpdate) AddCreatedBy(v int64) *EmailBroadcastUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *EmailBroadcastUpdate) ClearCreatedBy() *EmailBroadcastUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *EmailBroadcastUpdate) SetStartedAt(v time.Time) *EmailBroadcastUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableStartedAt(v *time.Time) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *EmailBroadcastUpdate) ClearStartedAt() *EmailBroadcastUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *EmailBroadcastUpdate) SetFinishedAt(v time.Time) *EmailBroadcastUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *EmailBroadcastUpdate) SetNillableFinishedAt(v *time.Time) *EmailBroadcastUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *EmailBroadcastUpdate) ClearFinishedAt() *EmailBroadcastUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailBroadcastUpdate) SetUpdatedAt(v time.Time) *EmailBroadcastUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EmailBroadcastMutation object of the builder.
func (_u *EmailBroadcastUpdate) Mutation() *EmailBroadcastMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailBroadcastUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailBroadcastUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailBroadcastUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailBroadcastUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailBroadcastUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailbroadcast.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailBroadcastUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := emailbroadcast.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := emailbroadcast.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodyFormat(); ok {
		if err := emailbroadcast.BodyFormatValidator(v); err != nil {
			return &ValidationError{Name: "body_format", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.body_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientsMode(); ok {
		if err := emailbroadcast.RecipientsModeValidator(v); err != nil {
			return &ValidationError{Name: "recipients_mode", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.recipients_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailbroadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalCount(); ok {
		if err := emailbroadcast.TotalCountValidator(v); err != nil {
			return &ValidationError{Name: "total_count", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.total_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SuccessCount(); ok {
		if err := emailbroadcast.SuccessCountValidator(v); err != nil {
			return &ValidationError{Name: "success_count", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.success_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailedCount(); ok {
		if err := emailbroadcast.FailedCountValidator(v); err != nil {
			return &ValidationError{Name: "failed_count", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.failed_count": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailBroadcastUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailbroadcast.Table, emailbroadcast.Columns, sqlgraph.NewFieldSpec(emailbroadcast.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(emailbroadcast.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(emailbroadcast.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyFormat(); ok {
		_spec.SetField(emailbroadcast.FieldBodyFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientsMode(); ok {
		_spec.SetField(emailbroadcast.FieldRecipientsMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientUserIds(); ok {
		_spec.SetField(emailbroadcast.FieldRecipientUserIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRecipientUserIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, emailbroadcast.FieldRecipientUserIds, value)
		})
	}
	if _u.mutation.RecipientUserIdsCleared() {
		_spec.ClearField(emailbroadcast.FieldRecipientUserIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailbroadcast.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(emailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(emailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(emailbroadcast.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(emailbroadcast.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(emailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(emailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(emailbroadcast.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(emailbroadcast.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(emailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(emailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(emailbroadcast.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(emailbroadcast.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(emailbroadcast.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(emailbroadcast.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(emailbroadcast.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailbroadcast.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailbroadcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailBroadcastUpdateOne is the builder for updating a single EmailBroadcast entity.
type EmailBroadcastUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailBroadcastMutation
}

// SetSubject sets the "subject" field.
func (_u *EmailBroadcastUpdateOne) SetSubject(v string) *EmailBroadcastUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableSubject(v *string) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *EmailBroadcastUpdateOne) SetBody(v string) *EmailBroadcastUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableBody(v *string) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetBodyFormat sets the "body_format" field.
func (_u *EmailBroadcastUpdateOne) SetBodyFormat(v string) *EmailBroadcastUpdateOne {
	_u.mutation.SetBodyFormat(v)
	return _u
}

// SetNillableBodyFormat sets the "body_format" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableBodyFormat(v *string) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetBodyFormat(*v)
	}
	return _u
}

// SetRecipientsMode sets the "recipients_mode" field.
func (_u *EmailBroadcastUpdateOne) SetRecipientsMode(v string) *EmailBroadcastUpdateOne {
	_u.mutation.SetRecipientsMode(v)
	return _u
}

// SetNillableRecipientsMode sets the "recipients_mode" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableRecipientsMode(v *string) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetRecipientsMode(*v)
	}
	return _u
}

// SetRecipientUserIds sets the "recipient_user_ids" field.
func (_u *EmailBroadcastUpdateOne) SetRecipientUserIds(v []int64) *EmailBroadcastUpdateOne {
	_u.mutation.SetRecipientUserIds(v)
	return _u
}

// AppendRecipientUserIds appends value to the "recipient_user_ids" field.
func (_u *EmailBroadcastUpdateOne) AppendRecipientUserIds(v []int64) *EmailBroadcastUpdateOne {
	_u.mutation.AppendRecipientUserIds(v)
	return _u
}

// ClearRecipientUserIds clears the value of the "recipient_user_ids" field.
func (_u *EmailBroadcastUpdateOne) ClearRecipientUserIds() *EmailBroadcastUpdateOne {
	_u.mutation.ClearRecipientUserIds()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EmailBroadcastUpdateOne) SetStatus(v string) *EmailBroadcastUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableStatus(v *string) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *EmailBroadcastUpdateOne) SetTotalCount(v int) *EmailBroadcastUpdateOne {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableTotalCount(v *int) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *EmailBroadcastUpdateOne) AddTotalCount(v int) *EmailBroadcastUpdateOne {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *EmailBroadcastUpdateOne) SetSuccessCount(v int) *EmailBroadcastUpdateOne {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableSuccessCount(v *int) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *EmailBroadcastUpdateOne) AddSuccessCount(v int) *EmailBroadcastUpdateOne {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *EmailBroadcastUpdateOne) SetFailedCount(v int) *EmailBroadcastUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableFailedCount(v *int) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *EmailBroadcastUpdateOne) AddFailedCount(v int) *EmailBroadcastUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EmailBroadcastUpdateOne) SetErrorMessage(v string) *EmailBroadcastUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableErrorMessage(v *string) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *EmailBroadcastUpdateOne) ClearErrorMessage() *EmailBroadcastUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EmailBroadcastUpdateOne) SetCreatedBy(v int64) *EmailBroadcastUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableCreatedBy(v *int64) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *EmailBroadcastUpdateOne) AddCreatedBy(v int64) *EmailBroadcastUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *EmailBroadcastUpdateOne) ClearCreatedBy() *EmailBroadcastUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *EmailBroadcastUpdateOne) SetStartedAt(v time.Time) *EmailBroadcastUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableStartedAt(v *time.Time) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *EmailBroadcastUpdateOne) ClearStartedAt() *EmailBroadcastUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *EmailBroadcastUpdateOne) SetFinishedAt(v time.Time) *EmailBroadcastUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *EmailBroadcastUpdateOne) SetNillableFinishedAt(v *time.Time) *EmailBroadcastUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *EmailBroadcastUpdateOne) ClearFinishedAt() *EmailBroadcastUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailBroadcastUpdateOne) SetUpdatedAt(v time.Time) *EmailBroadcastUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the EmailBroadcastMutation object of the builder.
func (_u *EmailBroadcastUpdateOne) Mutation() *EmailBroadcastMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailBroadcastUpdate builder.
func (_u *EmailBroadcastUpdateOne) Where(ps ...predicate.EmailBroadcast) *EmailBroadcastUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailBroadcastUpdateOne) Select(field string, fields ...string) *EmailBroadcastUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailBroadcast entity.
func (_u *EmailBroadcastUpdateOne) Save(ctx context.Context) (*EmailBroadcast, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailBroadcastUpdateOne) SaveX(ctx context.Context) *EmailBroadcast {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailBroadcastUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailBroadcastUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmailBroadcastUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := emailbroadcast.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailBroadcastUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := emailbroadcast.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := emailbroadcast.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodyFormat(); ok {
		if err := emailbroadcast.BodyFormatValidator(v); err != nil {
			return &ValidationError{Name: "body_format", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.body_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientsMode(); ok {
		if err := emailbroadcast.RecipientsModeValidator(v); err != nil {
			return &ValidationError{Name: "recipients_mode", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.recipients_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := emailbroadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalCount(); ok {
		if err := emailbroadcast.TotalCountValidator(v); err != nil {
			return &ValidationError{Name: "total_count", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.total_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SuccessCount(); ok {
		if err := emailbroadcast.SuccessCountValidator(v); err != nil {
			return &ValidationError{Name: "success_count", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.success_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailedCount(); ok {
		if err := emailbroadcast.FailedCountValidator(v); err != nil {
			return &ValidationError{Name: "failed_count", err: fmt.Errorf(`ent: validator failed for field "EmailBroadcast.failed_count": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailBroadcastUpdateOne) sqlSave(ctx context.Context) (_node *EmailBroadcast, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailbroadcast.Table, emailbroadcast.Columns, sqlgraph.NewFieldSpec(emailbroadcast.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailBroadcast.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailbroadcast.FieldID)
		for _, f := range fields {
			if !emailbroadcast.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailbroadcast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(emailbroadcast.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(emailbroadcast.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyFormat(); ok {
		_spec.SetField(emailbroadcast.FieldBodyFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientsMode(); ok {
		_spec.SetField(emailbroadcast.FieldRecipientsMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientUserIds(); ok {
		_spec.SetField(emailbroadcast.FieldRecipientUserIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRecipientUserIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, emailbroadcast.FieldRecipientUserIds, value)
		})
	}
	if _u.mutation.RecipientUserIdsCleared() {
		_spec.ClearField(emailbroadcast.FieldRecipientUserIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(emailbroadcast.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(emailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(emailbroadcast.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(emailbroadcast.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(emailbroadcast.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(emailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(emailbroadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(emailbroadcast.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(emailbroadcast.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(emailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(emailbroadcast.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(emailbroadcast.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(emailbroadcast.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(emailbroadcast.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(emailbroadcast.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(emailbroadcast.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailbroadcast.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &EmailBroadcast{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailbroadcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
