// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"ikik-api/ent/emailbroadcast"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EmailBroadcast is the model entity for the EmailBroadcast schema.
type EmailBroadcast struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 邮件主题
	Subject string `json:"subject,omitempty"`
	// 邮件正文 (HTML 或纯文本)
	Body string `json:"body,omitempty"`
	// 正文格式: html, text
	BodyFormat string `json:"body_format,omitempty"`
	// 收件人模式: all, selected
	RecipientsMode string `json:"recipients_mode,omitempty"`
	// 收件人用户 ID 列表 (selected 模式时使用)
	RecipientUserIds []int64 `json:"recipient_user_ids,omitempty"`
	// 状态: pending, sending, completed, failed
	Status string `json:"status,omitempty"`
	// 收件人总数
	TotalCount int `json:"total_count,omitempty"`
	// 发送成功数
	SuccessCount int `json:"success_count,omitempty"`
	// 发送失败数
	FailedCount int `json:"failed_count,omitempty"`
	// 整批失败原因 (status=failed 时填充)
	ErrorMessage *string `json:"error_message,omitempty"`
	// 创建管理员用户 ID
	CreatedBy *int64 `json:"created_by,omitempty"`
	// 开始发送时间
	StartedAt *time.Time `json:"started_at,omitempty"`
	// 发送结束时间
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailBroadcast) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailbroadcast.FieldRecipientUserIds:
			values[i] = new([]byte)
		case emailbroadcast.FieldID, emailbroadcast.FieldTotalCount, emailbroadcast.FieldSuccessCount, emailbroadcast.FieldFailedCount, emailbroadcast.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case emailbroadcast.FieldSubject, emailbroadcast.FieldBody, emailbroadcast.FieldBodyFormat, emailbroadcast.FieldRecipientsMode, emailbroadcast.FieldStatus, emailbroadcast.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case emailbroadcast.FieldStartedAt, emailbroadcast.FieldFinishedAt, emailbroadcast.FieldCreatedAt, emailbroadcast.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailBroadcast fields.
func (_m *EmailBroadcast) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailbroadcast.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case emailbroadcast.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case emailbroadcast.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case emailbroadcast.FieldBodyFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body_format", values[i])
			} else if value.Valid {
				_m.BodyFormat = value.String
			}
		case emailbroadcast.FieldRecipientsMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipients_mode", values[i])
			} else if value.Valid {
				_m.RecipientsMode = value.String
			}
		case emailbroadcast.FieldRecipientUserIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_user_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RecipientUserIds); err != nil {
					return fmt.Errorf("unmarshal field recipient_user_ids: %w", err)
				}
			}
		case emailbroadcast.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case emailbroadcast.FieldTotalCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_count", values[i])
			} else if value.Valid {
				_m.TotalCount = int(value.Int64)
			}
		case emailbroadcast.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = int(value.Int64)
			}
		case emailbroadcast.FieldFailedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_count", values[i])
			} else if value.Valid {
				_m.FailedCount = int(value.Int64)
			}
		case emailbroadcast.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case emailbroadcast.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case emailbroadcast.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case emailbroadcast.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case emailbroadcast.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emailbroadcast.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailBroadcast.
// This includes values selected through modifiers, order, etc.
func (_m *EmailBroadcast) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EmailBroadcast.
// Note that you need to call EmailBroadcast.Unwrap() before calling this method if this EmailBroadcast
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailBroadcast) Update() *EmailBroadcastUpdateOne {
	return NewEmailBroadcastClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailBroadcast entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailBroadcast) Unwrap() *EmailBroadcast {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailBroadcast is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailBroadcast) String() string {
	var builder strings.Builder
	builder.WriteString("EmailBroadcast(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("body_format=")
	builder.WriteString(_m.BodyFormat)
	builder.WriteString(", ")
	builder.WriteString("recipients_mode=")
	builder.WriteString(_m.RecipientsMode)
	builder.WriteString(", ")
	builder.WriteString("recipient_user_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecipientUserIds))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("total_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCount))
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("failed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedCount))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmailBroadcasts is a parsable slice of EmailBroadcast.
type EmailBroadcasts []*EmailBroadcast
