// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/predicate"
	"ikik-api/ent/shopcategory"
	"ikik-api/ent/shopproduct"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopCategoryUpdate is the builder for updating ShopCategory entities.
type ShopCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *ShopCategoryMutation
}

// Where appends a list predicates to the ShopCategoryUpdate builder.
func (_u *ShopCategoryUpdate) Where(ps ...predicate.ShopCategory) *ShopCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShopCategoryUpdate) SetUpdatedAt(v time.Time) *ShopCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ShopCategoryUpdate) SetName(v string) *ShopCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ShopCategoryUpdate) SetNillableName(v *string) *ShopCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ShopCategoryUpdate) SetIcon(v string) *ShopCategoryUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ShopCategoryUpdate) SetNillableIcon(v *string) *ShopCategoryUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *ShopCategoryUpdate) ClearIcon() *ShopCategoryUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ShopCategoryUpdate) SetSortOrder(v int) *ShopCategoryUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ShopCategoryUpdate) SetNillableSortOrder(v *int) *ShopCategoryUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ShopCategoryUpdate) AddSortOrder(v int) *ShopCategoryUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ShopCategoryUpdate) SetEnabled(v bool) *ShopCategoryUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ShopCategoryUpdate) SetNillableEnabled(v *bool) *ShopCategoryUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ShopCategoryUpdate) SetDescription(v string) *ShopCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ShopCategoryUpdate) SetNillableDescription(v *string) *ShopCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ShopCategoryUpdate) ClearDescription() *ShopCategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddProductIDs adds the "products" edge to the ShopProduct entity by IDs.
func (_u *ShopCategoryUpdate) AddProductIDs(ids ...int64) *ShopCategoryUpdate {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the ShopProduct entity.
func (_u *ShopCategoryUpdate) AddProducts(v ...*ShopProduct) *ShopCategoryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// Mutation returns the ShopCategoryMutation object of the builder.
func (_u *ShopCategoryUpdate) Mutation() *ShopCategoryMutation {
	return _u.mutation
}

// ClearProducts clears all "products" edges to the ShopProduct entity.
func (_u *ShopCategoryUpdate) ClearProducts() *ShopCategoryUpdate {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to ShopProduct entities by IDs.
func (_u *ShopCategoryUpdate) RemoveProductIDs(ids ...int64) *ShopCategoryUpdate {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to ShopProduct entities.
func (_u *ShopCategoryUpdate) RemoveProducts(v ...*ShopProduct) *ShopCategoryUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShopCategoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShopCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShopCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShopCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShopCategoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shopcategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShopCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := shopcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ShopCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := shopcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ShopCategory.icon": %w`, err)}
		}
	}
	return nil
}

func (_u *ShopCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shopcategory.Table, shopcategory.Columns, sqlgraph.NewFieldSpec(shopcategory.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shopcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(shopcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(shopcategory.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(shopcategory.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(shopcategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(shopcategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(shopcategory.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(shopcategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(shopcategory.FieldDescription, field.TypeString)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShopCategoryUpdateOne is the builder for updating a single ShopCategory entity.
type ShopCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShopCategoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShopCategoryUpdateOne) SetUpdatedAt(v time.Time) *ShopCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ShopCategoryUpdateOne) SetName(v string) *ShopCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ShopCategoryUpdateOne) SetNillableName(v *string) *ShopCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ShopCategoryUpdateOne) SetIcon(v string) *ShopCategoryUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ShopCategoryUpdateOne) SetNillableIcon(v *string) *ShopCategoryUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *ShopCategoryUpdateOne) ClearIcon() *ShopCategoryUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ShopCategoryUpdateOne) SetSortOrder(v int) *ShopCategoryUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ShopCategoryUpdateOne) SetNillableSortOrder(v *int) *ShopCategoryUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ShopCategoryUpdateOne) AddSortOrder(v int) *ShopCategoryUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ShopCategoryUpdateOne) SetEnabled(v bool) *ShopCategoryUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ShopCategoryUpdateOne) SetNillableEnabled(v *bool) *ShopCategoryUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ShopCategoryUpdateOne) SetDescription(v string) *ShopCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ShopCategoryUpdateOne) SetNillableDescription(v *string) *ShopCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ShopCategoryUpdateOne) ClearDescription() *ShopCategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddProductIDs adds the "products" edge to the ShopProduct entity by IDs.
func (_u *ShopCategoryUpdateOne) AddProductIDs(ids ...int64) *ShopCategoryUpdateOne {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the ShopProduct entity.
func (_u *ShopCategoryUpdateOne) AddProducts(v ...*ShopProduct) *ShopCategoryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// Mutation returns the ShopCategoryMutation object of the builder.
func (_u *ShopCategoryUpdateOne) Mutation() *ShopCategoryMutation {
	return _u.mutation
}

// ClearProducts clears all "products" edges to the ShopProduct entity.
func (_u *ShopCategoryUpdateOne) ClearProducts() *ShopCategoryUpdateOne {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to ShopProduct entities by IDs.
func (_u *ShopCategoryUpdateOne) RemoveProductIDs(ids ...int64) *ShopCategoryUpdateOne {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to ShopProduct entities.
func (_u *ShopCategoryUpdateOne) RemoveProducts(v ...*ShopProduct) *ShopCategoryUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// Where appends a list predicates to the ShopCategoryUpdate builder.
func (_u *ShopCategoryUpdateOne) Where(ps ...predicate.ShopCategory) *ShopCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShopCategoryUpdateOne) Select(field string, fields ...string) *ShopCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ShopCategory entity.
func (_u *ShopCategoryUpdateOne) Save(ctx context.Context) (*ShopCategory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShopCategoryUpdateOne) SaveX(ctx context.Context) *ShopCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShopCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShopCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShopCategoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shopcategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShopCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := shopcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ShopCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := shopcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ShopCategory.icon": %w`, err)}
		}
	}
	return nil
}

func (_u *ShopCategoryUpdateOne) sqlSave(ctx context.Context) (_node *ShopCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shopcategory.Table, shopcategory.Columns, sqlgraph.NewFieldSpec(shopcategory.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ShopCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shopcategory.FieldID)
		for _, f := range fields {
			if !shopcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shopcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shopcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(shopcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(shopcategory.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(shopcategory.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(shopcategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(shopcategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(shopcategory.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(shopcategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(shopcategory.FieldDescription, field.TypeString)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ShopCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
