// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ikik-api/ent/predicate"
	"ikik-api/ent/shopproduct"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopProductDelete is the builder for deleting a ShopProduct entity.
type ShopProductDelete struct {
	config
	hooks    []Hook
	mutation *ShopProductMutation
}

// Where appends a list predicates to the ShopProductDelete builder.
func (_d *ShopProductDelete) Where(ps ...predicate.ShopProduct) *ShopProductDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ShopProductDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShopProductDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ShopProductDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shopproduct.Table, sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ShopProductDeleteOne is the builder for deleting a single ShopProduct entity.
type ShopProductDeleteOne struct {
	_d *ShopProductDelete
}

// Where appends a list predicates to the ShopProductDelete builder.
func (_d *ShopProductDeleteOne) Where(ps ...predicate.ShopProduct) *ShopProductDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ShopProductDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shopproduct.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShopProductDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
