// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/shopcardkey"
	"ikik-api/ent/shoporder"
	"ikik-api/ent/shopproduct"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopCardKeyCreate is the builder for creating a ShopCardKey entity.
type ShopCardKeyCreate struct {
	config
	mutation *ShopCardKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShopCardKeyCreate) SetCreatedAt(v time.Time) *ShopCardKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableCreatedAt(v *time.Time) *ShopCardKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShopCardKeyCreate) SetUpdatedAt(v time.Time) *ShopCardKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableUpdatedAt(v *time.Time) *ShopCardKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ShopCardKeyCreate) SetProductID(v int64) *ShopCardKeyCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ShopCardKeyCreate) SetContent(v string) *ShopCardKeyCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ShopCardKeyCreate) SetStatus(v string) *ShopCardKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableStatus(v *string) *ShopCardKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *ShopCardKeyCreate) SetOrderID(v int64) *ShopCardKeyCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableOrderID(v *int64) *ShopCardKeyCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetLockedAt sets the "locked_at" field.
func (_c *ShopCardKeyCreate) SetLockedAt(v time.Time) *ShopCardKeyCreate {
	_c.mutation.SetLockedAt(v)
	return _c
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableLockedAt(v *time.Time) *ShopCardKeyCreate {
	if v != nil {
		_c.SetLockedAt(*v)
	}
	return _c
}

// SetLockedUntil sets the "locked_until" field.
func (_c *ShopCardKeyCreate) SetLockedUntil(v time.Time) *ShopCardKeyCreate {
	_c.mutation.SetLockedUntil(v)
	return _c
}

// SetNillableLockedUntil sets the "locked_until" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableLockedUntil(v *time.Time) *ShopCardKeyCreate {
	if v != nil {
		_c.SetLockedUntil(*v)
	}
	return _c
}

// SetSoldAt sets the "sold_at" field.
func (_c *ShopCardKeyCreate) SetSoldAt(v time.Time) *ShopCardKeyCreate {
	_c.mutation.SetSoldAt(v)
	return _c
}

// SetNillableSoldAt sets the "sold_at" field if the given value is not nil.
func (_c *ShopCardKeyCreate) SetNillableSoldAt(v *time.Time) *ShopCardKeyCreate {
	if v != nil {
		_c.SetSoldAt(*v)
	}
	return _c
}

// SetProduct sets the "product" edge to the ShopProduct entity.
func (_c *ShopCardKeyCreate) SetProduct(v *ShopProduct) *ShopCardKeyCreate {
	return _c.SetProductID(v.ID)
}

// SetOrder sets the "order" edge to the ShopOrder entity.
func (_c *ShopCardKeyCreate) SetOrder(v *ShopOrder) *ShopCardKeyCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the ShopCardKeyMutation object of the builder.
func (_c *ShopCardKeyCreate) Mutation() *ShopCardKeyMutation {
	return _c.mutation
}

// Save creates the ShopCardKey in the database.
func (_c *ShopCardKeyCreate) Save(ctx context.Context) (*ShopCardKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShopCardKeyCreate) SaveX(ctx context.Context) *ShopCardKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopCardKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopCardKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShopCardKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shopcardkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shopcardkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := shopcardkey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShopCardKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShopCardKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ShopCardKey.updated_at"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "ShopCardKey.product_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ShopCardKey.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := shopcardkey.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ShopCardKey.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ShopCardKey.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := shopcardkey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ShopCardKey.status": %w`, err)}
		}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "ShopCardKey.product"`)}
	}
	return nil
}

func (_c *ShopCardKeyCreate) sqlSave(ctx context.Context) (*ShopCardKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShopCardKeyCreate) createSpec() (*ShopCardKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ShopCardKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shopcardkey.Table, sqlgraph.NewFieldSpec(shopcardkey.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shopcardkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shopcardkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(shopcardkey.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(shopcardkey.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LockedAt(); ok {
		_spec.SetField(shopcardkey.FieldLockedAt, field.TypeTime, value)
		_node.LockedAt = &value
	}
	if value, ok := _c.mutation.LockedUntil(); ok {
		_spec.SetField(shopcardkey.FieldLockedUntil, field.TypeTime, value)
		_node.LockedUntil = &value
	}
	if value, ok := _c.mutation.SoldAt(); ok {
		_spec.SetField(shopcardkey.FieldSoldAt, field.TypeTime, value)
		_node.SoldAt = &value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopcardkey.ProductTable,
			Columns: []string{shopcardkey.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopcardkey.OrderTable,
			Columns: []string{shopcardkey.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopCardKey.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopCardKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopCardKeyCreate) OnConflict(opts ...sql.ConflictOption) *ShopCardKeyUpsertOne {
	_c.conflict = opts
	return &ShopCardKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopCardKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopCardKeyCreate) OnConflictColumns(columns ...string) *ShopCardKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopCardKeyUpsertOne{
		create: _c,
	}
}

type (
	// ShopCardKeyUpsertOne is the builder for "upsert"-ing
	//  one ShopCardKey node.
	ShopCardKeyUpsertOne struct {
		create *ShopCardKeyCreate
	}

	// ShopCardKeyUpsert is the "OnConflict" setter.
	ShopCardKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopCardKeyUpsert) SetUpdatedAt(v time.Time) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateUpdatedAt() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldUpdatedAt)
	return u
}

// SetProductID sets the "product_id" field.
func (u *ShopCardKeyUpsert) SetProductID(v int64) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateProductID() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldProductID)
	return u
}

// SetContent sets the "content" field.
func (u *ShopCardKeyUpsert) SetContent(v string) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateContent() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldContent)
	return u
}

// SetStatus sets the "status" field.
func (u *ShopCardKeyUpsert) SetStatus(v string) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateStatus() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldStatus)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *ShopCardKeyUpsert) SetOrderID(v int64) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateOrderID() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldOrderID)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *ShopCardKeyUpsert) ClearOrderID() *ShopCardKeyUpsert {
	u.SetNull(shopcardkey.FieldOrderID)
	return u
}

// SetLockedAt sets the "locked_at" field.
func (u *ShopCardKeyUpsert) SetLockedAt(v time.Time) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldLockedAt, v)
	return u
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateLockedAt() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldLockedAt)
	return u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *ShopCardKeyUpsert) ClearLockedAt() *ShopCardKeyUpsert {
	u.SetNull(shopcardkey.FieldLockedAt)
	return u
}

// SetLockedUntil sets the "locked_until" field.
func (u *ShopCardKeyUpsert) SetLockedUntil(v time.Time) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldLockedUntil, v)
	return u
}

// UpdateLockedUntil sets the "locked_until" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateLockedUntil() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldLockedUntil)
	return u
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (u *ShopCardKeyUpsert) ClearLockedUntil() *ShopCardKeyUpsert {
	u.SetNull(shopcardkey.FieldLockedUntil)
	return u
}

// SetSoldAt sets the "sold_at" field.
func (u *ShopCardKeyUpsert) SetSoldAt(v time.Time) *ShopCardKeyUpsert {
	u.Set(shopcardkey.FieldSoldAt, v)
	return u
}

// UpdateSoldAt sets the "sold_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsert) UpdateSoldAt() *ShopCardKeyUpsert {
	u.SetExcluded(shopcardkey.FieldSoldAt)
	return u
}

// ClearSoldAt clears the value of the "sold_at" field.
func (u *ShopCardKeyUpsert) ClearSoldAt() *ShopCardKeyUpsert {
	u.SetNull(shopcardkey.FieldSoldAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ShopCardKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopCardKeyUpsertOne) UpdateNewValues() *ShopCardKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(shopcardkey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopCardKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShopCardKeyUpsertOne) Ignore() *ShopCardKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopCardKeyUpsertOne) DoNothing() *ShopCardKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopCardKeyCreate.OnConflict
// documentation for more info.
func (u *ShopCardKeyUpsertOne) Update(set func(*ShopCardKeyUpsert)) *ShopCardKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopCardKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopCardKeyUpsertOne) SetUpdatedAt(v time.Time) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateUpdatedAt() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *ShopCardKeyUpsertOne) SetProductID(v int64) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateProductID() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateProductID()
	})
}

// SetContent sets the "content" field.
func (u *ShopCardKeyUpsertOne) SetContent(v string) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateContent() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *ShopCardKeyUpsertOne) SetStatus(v string) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateStatus() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetOrderID sets the "order_id" field.
func (u *ShopCardKeyUpsertOne) SetOrderID(v int64) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateOrderID() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *ShopCardKeyUpsertOne) ClearOrderID() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearOrderID()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *ShopCardKeyUpsertOne) SetLockedAt(v time.Time) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateLockedAt() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *ShopCardKeyUpsertOne) ClearLockedAt() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearLockedAt()
	})
}

// SetLockedUntil sets the "locked_until" field.
func (u *ShopCardKeyUpsertOne) SetLockedUntil(v time.Time) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetLockedUntil(v)
	})
}

// UpdateLockedUntil sets the "locked_until" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateLockedUntil() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateLockedUntil()
	})
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (u *ShopCardKeyUpsertOne) ClearLockedUntil() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearLockedUntil()
	})
}

// SetSoldAt sets the "sold_at" field.
func (u *ShopCardKeyUpsertOne) SetSoldAt(v time.Time) *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetSoldAt(v)
	})
}

// UpdateSoldAt sets the "sold_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsertOne) UpdateSoldAt() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateSoldAt()
	})
}

// ClearSoldAt clears the value of the "sold_at" field.
func (u *ShopCardKeyUpsertOne) ClearSoldAt() *ShopCardKeyUpsertOne {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearSoldAt()
	})
}

// Exec executes the query.
func (u *ShopCardKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopCardKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopCardKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShopCardKeyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShopCardKeyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShopCardKeyCreateBulk is the builder for creating many ShopCardKey entities in bulk.
type ShopCardKeyCreateBulk struct {
	config
	err      error
	builders []*ShopCardKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the ShopCardKey entities in the database.
func (_c *ShopCardKeyCreateBulk) Save(ctx context.Context) ([]*ShopCardKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShopCardKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShopCardKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShopCardKeyCreateBulk) SaveX(ctx context.Context) []*ShopCardKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopCardKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopCardKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopCardKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopCardKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopCardKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShopCardKeyUpsertBulk {
	_c.conflict = opts
	return &ShopCardKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopCardKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopCardKeyCreateBulk) OnConflictColumns(columns ...string) *ShopCardKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopCardKeyUpsertBulk{
		create: _c,
	}
}

// ShopCardKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of ShopCardKey nodes.
type ShopCardKeyUpsertBulk struct {
	create *ShopCardKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ShopCardKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopCardKeyUpsertBulk) UpdateNewValues() *ShopCardKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(shopcardkey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopCardKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShopCardKeyUpsertBulk) Ignore() *ShopCardKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopCardKeyUpsertBulk) DoNothing() *ShopCardKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopCardKeyCreateBulk.OnConflict
// documentation for more info.
func (u *ShopCardKeyUpsertBulk) Update(set func(*ShopCardKeyUpsert)) *ShopCardKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopCardKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopCardKeyUpsertBulk) SetUpdatedAt(v time.Time) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateUpdatedAt() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *ShopCardKeyUpsertBulk) SetProductID(v int64) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateProductID() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateProductID()
	})
}

// SetContent sets the "content" field.
func (u *ShopCardKeyUpsertBulk) SetContent(v string) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateContent() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *ShopCardKeyUpsertBulk) SetStatus(v string) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateStatus() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateStatus()
	})
}

// SetOrderID sets the "order_id" field.
func (u *ShopCardKeyUpsertBulk) SetOrderID(v int64) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateOrderID() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *ShopCardKeyUpsertBulk) ClearOrderID() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearOrderID()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *ShopCardKeyUpsertBulk) SetLockedAt(v time.Time) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateLockedAt() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *ShopCardKeyUpsertBulk) ClearLockedAt() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearLockedAt()
	})
}

// SetLockedUntil sets the "locked_until" field.
func (u *ShopCardKeyUpsertBulk) SetLockedUntil(v time.Time) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetLockedUntil(v)
	})
}

// UpdateLockedUntil sets the "locked_until" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateLockedUntil() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateLockedUntil()
	})
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (u *ShopCardKeyUpsertBulk) ClearLockedUntil() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearLockedUntil()
	})
}

// SetSoldAt sets the "sold_at" field.
func (u *ShopCardKeyUpsertBulk) SetSoldAt(v time.Time) *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.SetSoldAt(v)
	})
}

// UpdateSoldAt sets the "sold_at" field to the value that was provided on create.
func (u *ShopCardKeyUpsertBulk) UpdateSoldAt() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.UpdateSoldAt()
	})
}

// ClearSoldAt clears the value of the "sold_at" field.
func (u *ShopCardKeyUpsertBulk) ClearSoldAt() *ShopCardKeyUpsertBulk {
	return u.Update(func(s *ShopCardKeyUpsert) {
		s.ClearSoldAt()
	})
}

// Exec executes the query.
func (u *ShopCardKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShopCardKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopCardKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopCardKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
