// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/predicate"
	"ikik-api/ent/shopbalanceledger"
	"ikik-api/ent/shopdrawcycle"
	"ikik-api/ent/shoporder"
	"ikik-api/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopBalanceLedgerUpdate is the builder for updating ShopBalanceLedger entities.
type ShopBalanceLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *ShopBalanceLedgerMutation
}

// Where appends a list predicates to the ShopBalanceLedgerUpdate builder.
func (_u *ShopBalanceLedgerUpdate) Where(ps ...predicate.ShopBalanceLedger) *ShopBalanceLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShopBalanceLedgerUpdate) SetUpdatedAt(v time.Time) *ShopBalanceLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ShopBalanceLedgerUpdate) SetUserID(v int64) *ShopBalanceLedgerUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableUserID(v *int64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetShopOrderID sets the "shop_order_id" field.
func (_u *ShopBalanceLedgerUpdate) SetShopOrderID(v int64) *ShopBalanceLedgerUpdate {
	_u.mutation.SetShopOrderID(v)
	return _u
}

// SetNillableShopOrderID sets the "shop_order_id" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableShopOrderID(v *int64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetShopOrderID(*v)
	}
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *ShopBalanceLedgerUpdate) SetEntryType(v string) *ShopBalanceLedgerUpdate {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableEntryType(v *string) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetDebitAmount sets the "debit_amount" field.
func (_u *ShopBalanceLedgerUpdate) SetDebitAmount(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.ResetDebitAmount()
	_u.mutation.SetDebitAmount(v)
	return _u
}

// SetNillableDebitAmount sets the "debit_amount" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableDebitAmount(v *float64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetDebitAmount(*v)
	}
	return _u
}

// AddDebitAmount adds value to the "debit_amount" field.
func (_u *ShopBalanceLedgerUpdate) AddDebitAmount(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.AddDebitAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *ShopBalanceLedgerUpdate) SetCreditAmount(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableCreditAmount(v *float64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *ShopBalanceLedgerUpdate) AddCreditAmount(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *ShopBalanceLedgerUpdate) SetBalanceBefore(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableBalanceBefore(v *float64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *ShopBalanceLedgerUpdate) AddBalanceBefore(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *ShopBalanceLedgerUpdate) SetBalanceAfter(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableBalanceAfter(v *float64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *ShopBalanceLedgerUpdate) AddBalanceAfter(v float64) *ShopBalanceLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetDrawCycleID sets the "draw_cycle_id" field.
func (_u *ShopBalanceLedgerUpdate) SetDrawCycleID(v int64) *ShopBalanceLedgerUpdate {
	_u.mutation.SetDrawCycleID(v)
	return _u
}

// SetNillableDrawCycleID sets the "draw_cycle_id" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableDrawCycleID(v *int64) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetDrawCycleID(*v)
	}
	return _u
}

// ClearDrawCycleID clears the value of the "draw_cycle_id" field.
func (_u *ShopBalanceLedgerUpdate) ClearDrawCycleID() *ShopBalanceLedgerUpdate {
	_u.mutation.ClearDrawCycleID()
	return _u
}

// SetDrawCycleIndex sets the "draw_cycle_index" field.
func (_u *ShopBalanceLedgerUpdate) SetDrawCycleIndex(v int) *ShopBalanceLedgerUpdate {
	_u.mutation.ResetDrawCycleIndex()
	_u.mutation.SetDrawCycleIndex(v)
	return _u
}

// SetNillableDrawCycleIndex sets the "draw_cycle_index" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdate) SetNillableDrawCycleIndex(v *int) *ShopBalanceLedgerUpdate {
	if v != nil {
		_u.SetDrawCycleIndex(*v)
	}
	return _u
}

// AddDrawCycleIndex adds value to the "draw_cycle_index" field.
func (_u *ShopBalanceLedgerUpdate) AddDrawCycleIndex(v int) *ShopBalanceLedgerUpdate {
	_u.mutation.AddDrawCycleIndex(v)
	return _u
}

// ClearDrawCycleIndex clears the value of the "draw_cycle_index" field.
func (_u *ShopBalanceLedgerUpdate) ClearDrawCycleIndex() *ShopBalanceLedgerUpdate {
	_u.mutation.ClearDrawCycleIndex()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ShopBalanceLedgerUpdate) SetUser(v *User) *ShopBalanceLedgerUpdate {
	return _u.SetUserID(v.ID)
}

// SetShopOrder sets the "shop_order" edge to the ShopOrder entity.
func (_u *ShopBalanceLedgerUpdate) SetShopOrder(v *ShopOrder) *ShopBalanceLedgerUpdate {
	return _u.SetShopOrderID(v.ID)
}

// SetDrawCycle sets the "draw_cycle" edge to the ShopDrawCycle entity.
func (_u *ShopBalanceLedgerUpdate) SetDrawCycle(v *ShopDrawCycle) *ShopBalanceLedgerUpdate {
	return _u.SetDrawCycleID(v.ID)
}

// Mutation returns the ShopBalanceLedgerMutation object of the builder.
func (_u *ShopBalanceLedgerUpdate) Mutation() *ShopBalanceLedgerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ShopBalanceLedgerUpdate) ClearUser() *ShopBalanceLedgerUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearShopOrder clears the "shop_order" edge to the ShopOrder entity.
func (_u *ShopBalanceLedgerUpdate) ClearShopOrder() *ShopBalanceLedgerUpdate {
	_u.mutation.ClearShopOrder()
	return _u
}

// ClearDrawCycle clears the "draw_cycle" edge to the ShopDrawCycle entity.
func (_u *ShopBalanceLedgerUpdate) ClearDrawCycle() *ShopBalanceLedgerUpdate {
	_u.mutation.ClearDrawCycle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShopBalanceLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShopBalanceLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShopBalanceLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShopBalanceLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShopBalanceLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shopbalanceledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShopBalanceLedgerUpdate) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := shopbalanceledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "ShopBalanceLedger.entry_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ShopBalanceLedger.user"`)
	}
	if _u.mutation.ShopOrderCleared() && len(_u.mutation.ShopOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ShopBalanceLedger.shop_order"`)
	}
	return nil
}

func (_u *ShopBalanceLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shopbalanceledger.Table, shopbalanceledger.Columns, sqlgraph.NewFieldSpec(shopbalanceledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shopbalanceledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(shopbalanceledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DebitAmount(); ok {
		_spec.SetField(shopbalanceledger.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebitAmount(); ok {
		_spec.AddField(shopbalanceledger.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(shopbalanceledger.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(shopbalanceledger.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(shopbalanceledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(shopbalanceledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(shopbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(shopbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DrawCycleIndex(); ok {
		_spec.SetField(shopbalanceledger.FieldDrawCycleIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDrawCycleIndex(); ok {
		_spec.AddField(shopbalanceledger.FieldDrawCycleIndex, field.TypeInt, value)
	}
	if _u.mutation.DrawCycleIndexCleared() {
		_spec.ClearField(shopbalanceledger.FieldDrawCycleIndex, field.TypeInt)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.UserTable,
			Columns: []string{shopbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.UserTable,
			Columns: []string{shopbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShopOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.ShopOrderTable,
			Columns: []string{shopbalanceledger.ShopOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.ShopOrderTable,
			Columns: []string{shopbalanceledger.ShopOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrawCycleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.DrawCycleTable,
			Columns: []string{shopbalanceledger.DrawCycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopdrawcycle.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrawCycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.DrawCycleTable,
			Columns: []string{shopbalanceledger.DrawCycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopdrawcycle.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopbalanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShopBalanceLedgerUpdateOne is the builder for updating a single ShopBalanceLedger entity.
type ShopBalanceLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShopBalanceLedgerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShopBalanceLedgerUpdateOne) SetUpdatedAt(v time.Time) *ShopBalanceLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ShopBalanceLedgerUpdateOne) SetUserID(v int64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableUserID(v *int64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetShopOrderID sets the "shop_order_id" field.
func (_u *ShopBalanceLedgerUpdateOne) SetShopOrderID(v int64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.SetShopOrderID(v)
	return _u
}

// SetNillableShopOrderID sets the "shop_order_id" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableShopOrderID(v *int64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetShopOrderID(*v)
	}
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *ShopBalanceLedgerUpdateOne) SetEntryType(v string) *ShopBalanceLedgerUpdateOne {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableEntryType(v *string) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetDebitAmount sets the "debit_amount" field.
func (_u *ShopBalanceLedgerUpdateOne) SetDebitAmount(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.ResetDebitAmount()
	_u.mutation.SetDebitAmount(v)
	return _u
}

// SetNillableDebitAmount sets the "debit_amount" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableDebitAmount(v *float64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetDebitAmount(*v)
	}
	return _u
}

// AddDebitAmount adds value to the "debit_amount" field.
func (_u *ShopBalanceLedgerUpdateOne) AddDebitAmount(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.AddDebitAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *ShopBalanceLedgerUpdateOne) SetCreditAmount(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableCreditAmount(v *float64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *ShopBalanceLedgerUpdateOne) AddCreditAmount(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *ShopBalanceLedgerUpdateOne) SetBalanceBefore(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableBalanceBefore(v *float64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *ShopBalanceLedgerUpdateOne) AddBalanceBefore(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *ShopBalanceLedgerUpdateOne) SetBalanceAfter(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *ShopBalanceLedgerUpdateOne) AddBalanceAfter(v float64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetDrawCycleID sets the "draw_cycle_id" field.
func (_u *ShopBalanceLedgerUpdateOne) SetDrawCycleID(v int64) *ShopBalanceLedgerUpdateOne {
	_u.mutation.SetDrawCycleID(v)
	return _u
}

// SetNillableDrawCycleID sets the "draw_cycle_id" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableDrawCycleID(v *int64) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetDrawCycleID(*v)
	}
	return _u
}

// ClearDrawCycleID clears the value of the "draw_cycle_id" field.
func (_u *ShopBalanceLedgerUpdateOne) ClearDrawCycleID() *ShopBalanceLedgerUpdateOne {
	_u.mutation.ClearDrawCycleID()
	return _u
}

// SetDrawCycleIndex sets the "draw_cycle_index" field.
func (_u *ShopBalanceLedgerUpdateOne) SetDrawCycleIndex(v int) *ShopBalanceLedgerUpdateOne {
	_u.mutation.ResetDrawCycleIndex()
	_u.mutation.SetDrawCycleIndex(v)
	return _u
}

// SetNillableDrawCycleIndex sets the "draw_cycle_index" field if the given value is not nil.
func (_u *ShopBalanceLedgerUpdateOne) SetNillableDrawCycleIndex(v *int) *ShopBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetDrawCycleIndex(*v)
	}
	return _u
}

// AddDrawCycleIndex adds value to the "draw_cycle_index" field.
func (_u *ShopBalanceLedgerUpdateOne) AddDrawCycleIndex(v int) *ShopBalanceLedgerUpdateOne {
	_u.mutation.AddDrawCycleIndex(v)
	return _u
}

// ClearDrawCycleIndex clears the value of the "draw_cycle_index" field.
func (_u *ShopBalanceLedgerUpdateOne) ClearDrawCycleIndex() *ShopBalanceLedgerUpdateOne {
	_u.mutation.ClearDrawCycleIndex()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ShopBalanceLedgerUpdateOne) SetUser(v *User) *ShopBalanceLedgerUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetShopOrder sets the "shop_order" edge to the ShopOrder entity.
func (_u *ShopBalanceLedgerUpdateOne) SetShopOrder(v *ShopOrder) *ShopBalanceLedgerUpdateOne {
	return _u.SetShopOrderID(v.ID)
}

// SetDrawCycle sets the "draw_cycle" edge to the ShopDrawCycle entity.
func (_u *ShopBalanceLedgerUpdateOne) SetDrawCycle(v *ShopDrawCycle) *ShopBalanceLedgerUpdateOne {
	return _u.SetDrawCycleID(v.ID)
}

// Mutation returns the ShopBalanceLedgerMutation object of the builder.
func (_u *ShopBalanceLedgerUpdateOne) Mutation() *ShopBalanceLedgerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ShopBalanceLedgerUpdateOne) ClearUser() *ShopBalanceLedgerUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearShopOrder clears the "shop_order" edge to the ShopOrder entity.
func (_u *ShopBalanceLedgerUpdateOne) ClearShopOrder() *ShopBalanceLedgerUpdateOne {
	_u.mutation.ClearShopOrder()
	return _u
}

// ClearDrawCycle clears the "draw_cycle" edge to the ShopDrawCycle entity.
func (_u *ShopBalanceLedgerUpdateOne) ClearDrawCycle() *ShopBalanceLedgerUpdateOne {
	_u.mutation.ClearDrawCycle()
	return _u
}

// Where appends a list predicates to the ShopBalanceLedgerUpdate builder.
func (_u *ShopBalanceLedgerUpdateOne) Where(ps ...predicate.ShopBalanceLedger) *ShopBalanceLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShopBalanceLedgerUpdateOne) Select(field string, fields ...string) *ShopBalanceLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ShopBalanceLedger entity.
func (_u *ShopBalanceLedgerUpdateOne) Save(ctx context.Context) (*ShopBalanceLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShopBalanceLedgerUpdateOne) SaveX(ctx context.Context) *ShopBalanceLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShopBalanceLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShopBalanceLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShopBalanceLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shopbalanceledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShopBalanceLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := shopbalanceledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "ShopBalanceLedger.entry_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ShopBalanceLedger.user"`)
	}
	if _u.mutation.ShopOrderCleared() && len(_u.mutation.ShopOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ShopBalanceLedger.shop_order"`)
	}
	return nil
}

func (_u *ShopBalanceLedgerUpdateOne) sqlSave(ctx context.Context) (_node *ShopBalanceLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shopbalanceledger.Table, shopbalanceledger.Columns, sqlgraph.NewFieldSpec(shopbalanceledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ShopBalanceLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shopbalanceledger.FieldID)
		for _, f := range fields {
			if !shopbalanceledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shopbalanceledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shopbalanceledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(shopbalanceledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DebitAmount(); ok {
		_spec.SetField(shopbalanceledger.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebitAmount(); ok {
		_spec.AddField(shopbalanceledger.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(shopbalanceledger.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(shopbalanceledger.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(shopbalanceledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(shopbalanceledger.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(shopbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(shopbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DrawCycleIndex(); ok {
		_spec.SetField(shopbalanceledger.FieldDrawCycleIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDrawCycleIndex(); ok {
		_spec.AddField(shopbalanceledger.FieldDrawCycleIndex, field.TypeInt, value)
	}
	if _u.mutation.DrawCycleIndexCleared() {
		_spec.ClearField(shopbalanceledger.FieldDrawCycleIndex, field.TypeInt)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.UserTable,
			Columns: []string{shopbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.UserTable,
			Columns: []string{shopbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShopOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.ShopOrderTable,
			Columns: []string{shopbalanceledger.ShopOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.ShopOrderTable,
			Columns: []string{shopbalanceledger.ShopOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DrawCycleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.DrawCycleTable,
			Columns: []string{shopbalanceledger.DrawCycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopdrawcycle.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DrawCycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopbalanceledger.DrawCycleTable,
			Columns: []string{shopbalanceledger.DrawCycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopdrawcycle.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ShopBalanceLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shopbalanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
