// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ikik-api/ent/shopbalanceledger"
	"ikik-api/ent/shopdrawcycle"
	"ikik-api/ent/shoporder"
	"ikik-api/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ShopBalanceLedger is the model entity for the ShopBalanceLedger schema.
type ShopBalanceLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ShopOrderID holds the value of the "shop_order_id" field.
	ShopOrderID int64 `json:"shop_order_id,omitempty"`
	// EntryType holds the value of the "entry_type" field.
	EntryType string `json:"entry_type,omitempty"`
	// DebitAmount holds the value of the "debit_amount" field.
	DebitAmount float64 `json:"debit_amount,omitempty"`
	// CreditAmount holds the value of the "credit_amount" field.
	CreditAmount float64 `json:"credit_amount,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore float64 `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// DrawCycleID holds the value of the "draw_cycle_id" field.
	DrawCycleID *int64 `json:"draw_cycle_id,omitempty"`
	// DrawCycleIndex holds the value of the "draw_cycle_index" field.
	DrawCycleIndex *int `json:"draw_cycle_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShopBalanceLedgerQuery when eager-loading is set.
	Edges        ShopBalanceLedgerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShopBalanceLedgerEdges holds the relations/edges for other nodes in the graph.
type ShopBalanceLedgerEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// ShopOrder holds the value of the shop_order edge.
	ShopOrder *ShopOrder `json:"shop_order,omitempty"`
	// DrawCycle holds the value of the draw_cycle edge.
	DrawCycle *ShopDrawCycle `json:"draw_cycle,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopBalanceLedgerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ShopOrderOrErr returns the ShopOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopBalanceLedgerEdges) ShopOrderOrErr() (*ShopOrder, error) {
	if e.ShopOrder != nil {
		return e.ShopOrder, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: shoporder.Label}
	}
	return nil, &NotLoadedError{edge: "shop_order"}
}

// DrawCycleOrErr returns the DrawCycle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopBalanceLedgerEdges) DrawCycleOrErr() (*ShopDrawCycle, error) {
	if e.DrawCycle != nil {
		return e.DrawCycle, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: shopdrawcycle.Label}
	}
	return nil, &NotLoadedError{edge: "draw_cycle"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShopBalanceLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shopbalanceledger.FieldDebitAmount, shopbalanceledger.FieldCreditAmount, shopbalanceledger.FieldBalanceBefore, shopbalanceledger.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case shopbalanceledger.FieldID, shopbalanceledger.FieldUserID, shopbalanceledger.FieldShopOrderID, shopbalanceledger.FieldDrawCycleID, shopbalanceledger.FieldDrawCycleIndex:
			values[i] = new(sql.NullInt64)
		case shopbalanceledger.FieldEntryType:
			values[i] = new(sql.NullString)
		case shopbalanceledger.FieldCreatedAt, shopbalanceledger.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShopBalanceLedger fields.
func (_m *ShopBalanceLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shopbalanceledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case shopbalanceledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shopbalanceledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case shopbalanceledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case shopbalanceledger.FieldShopOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shop_order_id", values[i])
			} else if value.Valid {
				_m.ShopOrderID = value.Int64
			}
		case shopbalanceledger.FieldEntryType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_type", values[i])
			} else if value.Valid {
				_m.EntryType = value.String
			}
		case shopbalanceledger.FieldDebitAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field debit_amount", values[i])
			} else if value.Valid {
				_m.DebitAmount = value.Float64
			}
		case shopbalanceledger.FieldCreditAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_amount", values[i])
			} else if value.Valid {
				_m.CreditAmount = value.Float64
			}
		case shopbalanceledger.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.Float64
			}
		case shopbalanceledger.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case shopbalanceledger.FieldDrawCycleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_cycle_id", values[i])
			} else if value.Valid {
				_m.DrawCycleID = new(int64)
				*_m.DrawCycleID = value.Int64
			}
		case shopbalanceledger.FieldDrawCycleIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_cycle_index", values[i])
			} else if value.Valid {
				_m.DrawCycleIndex = new(int)
				*_m.DrawCycleIndex = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShopBalanceLedger.
// This includes values selected through modifiers, order, etc.
func (_m *ShopBalanceLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ShopBalanceLedger entity.
func (_m *ShopBalanceLedger) QueryUser() *UserQuery {
	return NewShopBalanceLedgerClient(_m.config).QueryUser(_m)
}

// QueryShopOrder queries the "shop_order" edge of the ShopBalanceLedger entity.
func (_m *ShopBalanceLedger) QueryShopOrder() *ShopOrderQuery {
	return NewShopBalanceLedgerClient(_m.config).QueryShopOrder(_m)
}

// QueryDrawCycle queries the "draw_cycle" edge of the ShopBalanceLedger entity.
func (_m *ShopBalanceLedger) QueryDrawCycle() *ShopDrawCycleQuery {
	return NewShopBalanceLedgerClient(_m.config).QueryDrawCycle(_m)
}

// Update returns a builder for updating this ShopBalanceLedger.
// Note that you need to call ShopBalanceLedger.Unwrap() before calling this method if this ShopBalanceLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShopBalanceLedger) Update() *ShopBalanceLedgerUpdateOne {
	return NewShopBalanceLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShopBalanceLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShopBalanceLedger) Unwrap() *ShopBalanceLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShopBalanceLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShopBalanceLedger) String() string {
	var builder strings.Builder
	builder.WriteString("ShopBalanceLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("shop_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopOrderID))
	builder.WriteString(", ")
	builder.WriteString("entry_type=")
	builder.WriteString(_m.EntryType)
	builder.WriteString(", ")
	builder.WriteString("debit_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DebitAmount))
	builder.WriteString(", ")
	builder.WriteString("credit_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditAmount))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	if v := _m.DrawCycleID; v != nil {
		builder.WriteString("draw_cycle_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DrawCycleIndex; v != nil {
		builder.WriteString("draw_cycle_index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ShopBalanceLedgers is a parsable slice of ShopBalanceLedger.
type ShopBalanceLedgers []*ShopBalanceLedger
