// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/shopcategory"
	"ikik-api/ent/shopproduct"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopCategoryCreate is the builder for creating a ShopCategory entity.
type ShopCategoryCreate struct {
	config
	mutation *ShopCategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShopCategoryCreate) SetCreatedAt(v time.Time) *ShopCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShopCategoryCreate) SetNillableCreatedAt(v *time.Time) *ShopCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShopCategoryCreate) SetUpdatedAt(v time.Time) *ShopCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShopCategoryCreate) SetNillableUpdatedAt(v *time.Time) *ShopCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ShopCategoryCreate) SetName(v string) *ShopCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ShopCategoryCreate) SetIcon(v string) *ShopCategoryCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ShopCategoryCreate) SetNillableIcon(v *string) *ShopCategoryCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ShopCategoryCreate) SetSortOrder(v int) *ShopCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ShopCategoryCreate) SetNillableSortOrder(v *int) *ShopCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ShopCategoryCreate) SetEnabled(v bool) *ShopCategoryCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ShopCategoryCreate) SetNillableEnabled(v *bool) *ShopCategoryCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ShopCategoryCreate) SetDescription(v string) *ShopCategoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ShopCategoryCreate) SetNillableDescription(v *string) *ShopCategoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddProductIDs adds the "products" edge to the ShopProduct entity by IDs.
func (_c *ShopCategoryCreate) AddProductIDs(ids ...int64) *ShopCategoryCreate {
	_c.mutation.AddProductIDs(ids...)
	return _c
}

// AddProducts adds the "products" edges to the ShopProduct entity.
func (_c *ShopCategoryCreate) AddProducts(v ...*ShopProduct) *ShopCategoryCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProductIDs(ids...)
}

// Mutation returns the ShopCategoryMutation object of the builder.
func (_c *ShopCategoryCreate) Mutation() *ShopCategoryMutation {
	return _c.mutation
}

// Save creates the ShopCategory in the database.
func (_c *ShopCategoryCreate) Save(ctx context.Context) (*ShopCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShopCategoryCreate) SaveX(ctx context.Context) *ShopCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShopCategoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shopcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shopcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := shopcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := shopcategory.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShopCategoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShopCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ShopCategory.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ShopCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := shopcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ShopCategory.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := shopcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ShopCategory.icon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ShopCategory.sort_order"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ShopCategory.enabled"`)}
	}
	return nil
}

func (_c *ShopCategoryCreate) sqlSave(ctx context.Context) (*ShopCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShopCategoryCreate) createSpec() (*ShopCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &ShopCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shopcategory.Table, sqlgraph.NewFieldSpec(shopcategory.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shopcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shopcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(shopcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(shopcategory.FieldIcon, field.TypeString, value)
		_node.Icon = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(shopcategory.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(shopcategory.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(shopcategory.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if nodes := _c.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopcategory.ProductsTable,
			Columns: []string{shopcategory.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopCategory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopCategoryCreate) OnConflict(opts ...sql.ConflictOption) *ShopCategoryUpsertOne {
	_c.conflict = opts
	return &ShopCategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopCategoryCreate) OnConflictColumns(columns ...string) *ShopCategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopCategoryUpsertOne{
		create: _c,
	}
}

type (
	// ShopCategoryUpsertOne is the builder for "upsert"-ing
	//  one ShopCategory node.
	ShopCategoryUpsertOne struct {
		create *ShopCategoryCreate
	}

	// ShopCategoryUpsert is the "OnConflict" setter.
	ShopCategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopCategoryUpsert) SetUpdatedAt(v time.Time) *ShopCategoryUpsert {
	u.Set(shopcategory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopCategoryUpsert) UpdateUpdatedAt() *ShopCategoryUpsert {
	u.SetExcluded(shopcategory.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *ShopCategoryUpsert) SetName(v string) *ShopCategoryUpsert {
	u.Set(shopcategory.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShopCategoryUpsert) UpdateName() *ShopCategoryUpsert {
	u.SetExcluded(shopcategory.FieldName)
	return u
}

// SetIcon sets the "icon" field.
func (u *ShopCategoryUpsert) SetIcon(v string) *ShopCategoryUpsert {
	u.Set(shopcategory.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ShopCategoryUpsert) UpdateIcon() *ShopCategoryUpsert {
	u.SetExcluded(shopcategory.FieldIcon)
	return u
}

// ClearIcon clears the value of the "icon" field.
func (u *ShopCategoryUpsert) ClearIcon() *ShopCategoryUpsert {
	u.SetNull(shopcategory.FieldIcon)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ShopCategoryUpsert) SetSortOrder(v int) *ShopCategoryUpsert {
	u.Set(shopcategory.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ShopCategoryUpsert) UpdateSortOrder() *ShopCategoryUpsert {
	u.SetExcluded(shopcategory.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ShopCategoryUpsert) AddSortOrder(v int) *ShopCategoryUpsert {
	u.Add(shopcategory.FieldSortOrder, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ShopCategoryUpsert) SetEnabled(v bool) *ShopCategoryUpsert {
	u.Set(shopcategory.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ShopCategoryUpsert) UpdateEnabled() *ShopCategoryUpsert {
	u.SetExcluded(shopcategory.FieldEnabled)
	return u
}

// SetDescription sets the "description" field.
func (u *ShopCategoryUpsert) SetDescription(v string) *ShopCategoryUpsert {
	u.Set(shopcategory.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ShopCategoryUpsert) UpdateDescription() *ShopCategoryUpsert {
	u.SetExcluded(shopcategory.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ShopCategoryUpsert) ClearDescription() *ShopCategoryUpsert {
	u.SetNull(shopcategory.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ShopCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopCategoryUpsertOne) UpdateNewValues() *ShopCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(shopcategory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopCategory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShopCategoryUpsertOne) Ignore() *ShopCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopCategoryUpsertOne) DoNothing() *ShopCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopCategoryCreate.OnConflict
// documentation for more info.
func (u *ShopCategoryUpsertOne) Update(set func(*ShopCategoryUpsert)) *ShopCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopCategoryUpsertOne) SetUpdatedAt(v time.Time) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopCategoryUpsertOne) UpdateUpdatedAt() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ShopCategoryUpsertOne) SetName(v string) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShopCategoryUpsertOne) UpdateName() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateName()
	})
}

// SetIcon sets the "icon" field.
func (u *ShopCategoryUpsertOne) SetIcon(v string) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ShopCategoryUpsertOne) UpdateIcon() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *ShopCategoryUpsertOne) ClearIcon() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.ClearIcon()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ShopCategoryUpsertOne) SetSortOrder(v int) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ShopCategoryUpsertOne) AddSortOrder(v int) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ShopCategoryUpsertOne) UpdateSortOrder() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ShopCategoryUpsertOne) SetEnabled(v bool) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ShopCategoryUpsertOne) UpdateEnabled() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateEnabled()
	})
}

// SetDescription sets the "description" field.
func (u *ShopCategoryUpsertOne) SetDescription(v string) *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ShopCategoryUpsertOne) UpdateDescription() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ShopCategoryUpsertOne) ClearDescription() *ShopCategoryUpsertOne {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *ShopCategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopCategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopCategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShopCategoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShopCategoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShopCategoryCreateBulk is the builder for creating many ShopCategory entities in bulk.
type ShopCategoryCreateBulk struct {
	config
	err      error
	builders []*ShopCategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the ShopCategory entities in the database.
func (_c *ShopCategoryCreateBulk) Save(ctx context.Context) ([]*ShopCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShopCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShopCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShopCategoryCreateBulk) SaveX(ctx context.Context) []*ShopCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopCategory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopCategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShopCategoryUpsertBulk {
	_c.conflict = opts
	return &ShopCategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopCategoryCreateBulk) OnConflictColumns(columns ...string) *ShopCategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopCategoryUpsertBulk{
		create: _c,
	}
}

// ShopCategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of ShopCategory nodes.
type ShopCategoryUpsertBulk struct {
	create *ShopCategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ShopCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopCategoryUpsertBulk) UpdateNewValues() *ShopCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(shopcategory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopCategory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShopCategoryUpsertBulk) Ignore() *ShopCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopCategoryUpsertBulk) DoNothing() *ShopCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopCategoryCreateBulk.OnConflict
// documentation for more info.
func (u *ShopCategoryUpsertBulk) Update(set func(*ShopCategoryUpsert)) *ShopCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopCategoryUpsertBulk) SetUpdatedAt(v time.Time) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopCategoryUpsertBulk) UpdateUpdatedAt() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ShopCategoryUpsertBulk) SetName(v string) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShopCategoryUpsertBulk) UpdateName() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateName()
	})
}

// SetIcon sets the "icon" field.
func (u *ShopCategoryUpsertBulk) SetIcon(v string) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ShopCategoryUpsertBulk) UpdateIcon() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *ShopCategoryUpsertBulk) ClearIcon() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.ClearIcon()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ShopCategoryUpsertBulk) SetSortOrder(v int) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ShopCategoryUpsertBulk) AddSortOrder(v int) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ShopCategoryUpsertBulk) UpdateSortOrder() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ShopCategoryUpsertBulk) SetEnabled(v bool) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ShopCategoryUpsertBulk) UpdateEnabled() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateEnabled()
	})
}

// SetDescription sets the "description" field.
func (u *ShopCategoryUpsertBulk) SetDescription(v string) *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ShopCategoryUpsertBulk) UpdateDescription() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ShopCategoryUpsertBulk) ClearDescription() *ShopCategoryUpsertBulk {
	return u.Update(func(s *ShopCategoryUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *ShopCategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShopCategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopCategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopCategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
