// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ikik-api/ent/predicate"
	"ikik-api/ent/shopcardkey"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopCardKeyDelete is the builder for deleting a ShopCardKey entity.
type ShopCardKeyDelete struct {
	config
	hooks    []Hook
	mutation *ShopCardKeyMutation
}

// Where appends a list predicates to the ShopCardKeyDelete builder.
func (_d *ShopCardKeyDelete) Where(ps ...predicate.ShopCardKey) *ShopCardKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ShopCardKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShopCardKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ShopCardKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shopcardkey.Table, sqlgraph.NewFieldSpec(shopcardkey.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ShopCardKeyDeleteOne is the builder for deleting a single ShopCardKey entity.
type ShopCardKeyDeleteOne struct {
	_d *ShopCardKeyDelete
}

// Where appends a list predicates to the ShopCardKeyDelete builder.
func (_d *ShopCardKeyDeleteOne) Where(ps ...predicate.ShopCardKey) *ShopCardKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ShopCardKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shopcardkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShopCardKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
