// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"ikik-api/ent/shopdrawcycle"
	"ikik-api/ent/shoporder"
	"ikik-api/ent/shopproduct"
	"ikik-api/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ShopOrder is the model entity for the ShopOrder schema.
type ShopOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int64 `json:"product_id,omitempty"`
	// ProductName holds the value of the "product_name" field.
	ProductName string `json:"product_name,omitempty"`
	// ProductCoverURL holds the value of the "product_cover_url" field.
	ProductCoverURL *string `json:"product_cover_url,omitempty"`
	// ProductDescription holds the value of the "product_description" field.
	ProductDescription *string `json:"product_description,omitempty"`
	// ProductType holds the value of the "product_type" field.
	ProductType string `json:"product_type,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice float64 `json:"unit_price,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// PointsAmount holds the value of the "points_amount" field.
	PointsAmount float64 `json:"points_amount,omitempty"`
	// PaymentMethod holds the value of the "payment_method" field.
	PaymentMethod string `json:"payment_method,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// DeliveredCards holds the value of the "delivered_cards" field.
	DeliveredCards []string `json:"delivered_cards,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt *time.Time `json:"cancelled_at,omitempty"`
	// FailedReason holds the value of the "failed_reason" field.
	FailedReason *string `json:"failed_reason,omitempty"`
	// DrawRewardAmount holds the value of the "draw_reward_amount" field.
	DrawRewardAmount *float64 `json:"draw_reward_amount,omitempty"`
	// DrawCycleID holds the value of the "draw_cycle_id" field.
	DrawCycleID *int64 `json:"draw_cycle_id,omitempty"`
	// DrawCycleIndex holds the value of the "draw_cycle_index" field.
	DrawCycleIndex *int `json:"draw_cycle_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShopOrderQuery when eager-loading is set.
	Edges        ShopOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShopOrderEdges holds the relations/edges for other nodes in the graph.
type ShopOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Product holds the value of the product edge.
	Product *ShopProduct `json:"product,omitempty"`
	// DrawCycle holds the value of the draw_cycle edge.
	DrawCycle *ShopDrawCycle `json:"draw_cycle,omitempty"`
	// BalanceLedger holds the value of the balance_ledger edge.
	BalanceLedger []*ShopBalanceLedger `json:"balance_ledger,omitempty"`
	// CardKeys holds the value of the card_keys edge.
	CardKeys []*ShopCardKey `json:"card_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopOrderEdges) ProductOrErr() (*ShopProduct, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: shopproduct.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// DrawCycleOrErr returns the DrawCycle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopOrderEdges) DrawCycleOrErr() (*ShopDrawCycle, error) {
	if e.DrawCycle != nil {
		return e.DrawCycle, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: shopdrawcycle.Label}
	}
	return nil, &NotLoadedError{edge: "draw_cycle"}
}

// BalanceLedgerOrErr returns the BalanceLedger value or an error if the edge
// was not loaded in eager-loading.
func (e ShopOrderEdges) BalanceLedgerOrErr() ([]*ShopBalanceLedger, error) {
	if e.loadedTypes[3] {
		return e.BalanceLedger, nil
	}
	return nil, &NotLoadedError{edge: "balance_ledger"}
}

// CardKeysOrErr returns the CardKeys value or an error if the edge
// was not loaded in eager-loading.
func (e ShopOrderEdges) CardKeysOrErr() ([]*ShopCardKey, error) {
	if e.loadedTypes[4] {
		return e.CardKeys, nil
	}
	return nil, &NotLoadedError{edge: "card_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShopOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shoporder.FieldDeliveredCards:
			values[i] = new([]byte)
		case shoporder.FieldUnitPrice, shoporder.FieldTotalAmount, shoporder.FieldPointsAmount, shoporder.FieldDrawRewardAmount:
			values[i] = new(sql.NullFloat64)
		case shoporder.FieldID, shoporder.FieldUserID, shoporder.FieldProductID, shoporder.FieldQuantity, shoporder.FieldPaymentOrderID, shoporder.FieldDrawCycleID, shoporder.FieldDrawCycleIndex:
			values[i] = new(sql.NullInt64)
		case shoporder.FieldOrderNo, shoporder.FieldProductName, shoporder.FieldProductCoverURL, shoporder.FieldProductDescription, shoporder.FieldProductType, shoporder.FieldPaymentMethod, shoporder.FieldStatus, shoporder.FieldFailedReason:
			values[i] = new(sql.NullString)
		case shoporder.FieldCreatedAt, shoporder.FieldUpdatedAt, shoporder.FieldPaidAt, shoporder.FieldCompletedAt, shoporder.FieldCancelledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShopOrder fields.
func (_m *ShopOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shoporder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case shoporder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shoporder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case shoporder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case shoporder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case shoporder.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = value.Int64
			}
		case shoporder.FieldProductName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_name", values[i])
			} else if value.Valid {
				_m.ProductName = value.String
			}
		case shoporder.FieldProductCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_cover_url", values[i])
			} else if value.Valid {
				_m.ProductCoverURL = new(string)
				*_m.ProductCoverURL = value.String
			}
		case shoporder.FieldProductDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_description", values[i])
			} else if value.Valid {
				_m.ProductDescription = new(string)
				*_m.ProductDescription = value.String
			}
		case shoporder.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = value.String
			}
		case shoporder.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Float64
			}
		case shoporder.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case shoporder.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case shoporder.FieldPointsAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field points_amount", values[i])
			} else if value.Valid {
				_m.PointsAmount = value.Float64
			}
		case shoporder.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = value.String
			}
		case shoporder.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case shoporder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case shoporder.FieldDeliveredCards:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field delivered_cards", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DeliveredCards); err != nil {
					return fmt.Errorf("unmarshal field delivered_cards: %w", err)
				}
			}
		case shoporder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case shoporder.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case shoporder.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(time.Time)
				*_m.CancelledAt = value.Time
			}
		case shoporder.FieldFailedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failed_reason", values[i])
			} else if value.Valid {
				_m.FailedReason = new(string)
				*_m.FailedReason = value.String
			}
		case shoporder.FieldDrawRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_reward_amount", values[i])
			} else if value.Valid {
				_m.DrawRewardAmount = new(float64)
				*_m.DrawRewardAmount = value.Float64
			}
		case shoporder.FieldDrawCycleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_cycle_id", values[i])
			} else if value.Valid {
				_m.DrawCycleID = new(int64)
				*_m.DrawCycleID = value.Int64
			}
		case shoporder.FieldDrawCycleIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_cycle_index", values[i])
			} else if value.Valid {
				_m.DrawCycleIndex = new(int)
				*_m.DrawCycleIndex = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShopOrder.
// This includes values selected through modifiers, order, etc.
func (_m *ShopOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ShopOrder entity.
func (_m *ShopOrder) QueryUser() *UserQuery {
	return NewShopOrderClient(_m.config).QueryUser(_m)
}

// QueryProduct queries the "product" edge of the ShopOrder entity.
func (_m *ShopOrder) QueryProduct() *ShopProductQuery {
	return NewShopOrderClient(_m.config).QueryProduct(_m)
}

// QueryDrawCycle queries the "draw_cycle" edge of the ShopOrder entity.
func (_m *ShopOrder) QueryDrawCycle() *ShopDrawCycleQuery {
	return NewShopOrderClient(_m.config).QueryDrawCycle(_m)
}

// QueryBalanceLedger queries the "balance_ledger" edge of the ShopOrder entity.
func (_m *ShopOrder) QueryBalanceLedger() *ShopBalanceLedgerQuery {
	return NewShopOrderClient(_m.config).QueryBalanceLedger(_m)
}

// QueryCardKeys queries the "card_keys" edge of the ShopOrder entity.
func (_m *ShopOrder) QueryCardKeys() *ShopCardKeyQuery {
	return NewShopOrderClient(_m.config).QueryCardKeys(_m)
}

// Update returns a builder for updating this ShopOrder.
// Note that you need to call ShopOrder.Unwrap() before calling this method if this ShopOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShopOrder) Update() *ShopOrderUpdateOne {
	return NewShopOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShopOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShopOrder) Unwrap() *ShopOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShopOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShopOrder) String() string {
	var builder strings.Builder
	builder.WriteString("ShopOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("product_name=")
	builder.WriteString(_m.ProductName)
	builder.WriteString(", ")
	if v := _m.ProductCoverURL; v != nil {
		builder.WriteString("product_cover_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProductDescription; v != nil {
		builder.WriteString("product_description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(_m.ProductType)
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("points_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PointsAmount))
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(_m.PaymentMethod)
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("delivered_cards=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeliveredCards))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FailedReason; v != nil {
		builder.WriteString("failed_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DrawRewardAmount; v != nil {
		builder.WriteString("draw_reward_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DrawCycleID; v != nil {
		builder.WriteString("draw_cycle_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DrawCycleIndex; v != nil {
		builder.WriteString("draw_cycle_index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ShopOrders is a parsable slice of ShopOrder.
type ShopOrders []*ShopOrder
