// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ikik-api/ent/predicate"
	"ikik-api/ent/shopbalanceledger"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopBalanceLedgerDelete is the builder for deleting a ShopBalanceLedger entity.
type ShopBalanceLedgerDelete struct {
	config
	hooks    []Hook
	mutation *ShopBalanceLedgerMutation
}

// Where appends a list predicates to the ShopBalanceLedgerDelete builder.
func (_d *ShopBalanceLedgerDelete) Where(ps ...predicate.ShopBalanceLedger) *ShopBalanceLedgerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ShopBalanceLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShopBalanceLedgerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ShopBalanceLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shopbalanceledger.Table, sqlgraph.NewFieldSpec(shopbalanceledger.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ShopBalanceLedgerDeleteOne is the builder for deleting a single ShopBalanceLedger entity.
type ShopBalanceLedgerDeleteOne struct {
	_d *ShopBalanceLedgerDelete
}

// Where appends a list predicates to the ShopBalanceLedgerDelete builder.
func (_d *ShopBalanceLedgerDeleteOne) Where(ps ...predicate.ShopBalanceLedger) *ShopBalanceLedgerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ShopBalanceLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shopbalanceledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShopBalanceLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
