// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ikik-api/ent/shopbalanceledger"
	"ikik-api/ent/shopdrawcycle"
	"ikik-api/ent/shoporder"
	"ikik-api/ent/shopproduct"
	"ikik-api/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopDrawCycleCreate is the builder for creating a ShopDrawCycle entity.
type ShopDrawCycleCreate struct {
	config
	mutation *ShopDrawCycleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShopDrawCycleCreate) SetCreatedAt(v time.Time) *ShopDrawCycleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShopDrawCycleCreate) SetNillableCreatedAt(v *time.Time) *ShopDrawCycleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShopDrawCycleCreate) SetUpdatedAt(v time.Time) *ShopDrawCycleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShopDrawCycleCreate) SetNillableUpdatedAt(v *time.Time) *ShopDrawCycleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ShopDrawCycleCreate) SetUserID(v int64) *ShopDrawCycleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ShopDrawCycleCreate) SetProductID(v int64) *ShopDrawCycleCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetCycleNo sets the "cycle_no" field.
func (_c *ShopDrawCycleCreate) SetCycleNo(v int) *ShopDrawCycleCreate {
	_c.mutation.SetCycleNo(v)
	return _c
}

// SetGuaranteeCount sets the "guarantee_count" field.
func (_c *ShopDrawCycleCreate) SetGuaranteeCount(v int) *ShopDrawCycleCreate {
	_c.mutation.SetGuaranteeCount(v)
	return _c
}

// SetTargetAmount sets the "target_amount" field.
func (_c *ShopDrawCycleCreate) SetTargetAmount(v float64) *ShopDrawCycleCreate {
	_c.mutation.SetTargetAmount(v)
	return _c
}

// SetRemainingAmounts sets the "remaining_amounts" field.
func (_c *ShopDrawCycleCreate) SetRemainingAmounts(v []float64) *ShopDrawCycleCreate {
	_c.mutation.SetRemainingAmounts(v)
	return _c
}

// SetDrawnCount sets the "drawn_count" field.
func (_c *ShopDrawCycleCreate) SetDrawnCount(v int) *ShopDrawCycleCreate {
	_c.mutation.SetDrawnCount(v)
	return _c
}

// SetNillableDrawnCount sets the "drawn_count" field if the given value is not nil.
func (_c *ShopDrawCycleCreate) SetNillableDrawnCount(v *int) *ShopDrawCycleCreate {
	if v != nil {
		_c.SetDrawnCount(*v)
	}
	return _c
}

// SetDrawnAmount sets the "drawn_amount" field.
func (_c *ShopDrawCycleCreate) SetDrawnAmount(v float64) *ShopDrawCycleCreate {
	_c.mutation.SetDrawnAmount(v)
	return _c
}

// SetNillableDrawnAmount sets the "drawn_amount" field if the given value is not nil.
func (_c *ShopDrawCycleCreate) SetNillableDrawnAmount(v *float64) *ShopDrawCycleCreate {
	if v != nil {
		_c.SetDrawnAmount(*v)
	}
	return _c
}

// SetCompleted sets the "completed" field.
func (_c *ShopDrawCycleCreate) SetCompleted(v bool) *ShopDrawCycleCreate {
	_c.mutation.SetCompleted(v)
	return _c
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_c *ShopDrawCycleCreate) SetNillableCompleted(v *bool) *ShopDrawCycleCreate {
	if v != nil {
		_c.SetCompleted(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ShopDrawCycleCreate) SetUser(v *User) *ShopDrawCycleCreate {
	return _c.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the ShopProduct entity.
func (_c *ShopDrawCycleCreate) SetProduct(v *ShopProduct) *ShopDrawCycleCreate {
	return _c.SetProductID(v.ID)
}

// AddOrderIDs adds the "orders" edge to the ShopOrder entity by IDs.
func (_c *ShopDrawCycleCreate) AddOrderIDs(ids ...int64) *ShopDrawCycleCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the ShopOrder entity.
func (_c *ShopDrawCycleCreate) AddOrders(v ...*ShopOrder) *ShopDrawCycleCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// AddBalanceLedgerIDs adds the "balance_ledger" edge to the ShopBalanceLedger entity by IDs.
func (_c *ShopDrawCycleCreate) AddBalanceLedgerIDs(ids ...int64) *ShopDrawCycleCreate {
	_c.mutation.AddBalanceLedgerIDs(ids...)
	return _c
}

// AddBalanceLedger adds the "balance_ledger" edges to the ShopBalanceLedger entity.
func (_c *ShopDrawCycleCreate) AddBalanceLedger(v ...*ShopBalanceLedger) *ShopDrawCycleCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBalanceLedgerIDs(ids...)
}

// Mutation returns the ShopDrawCycleMutation object of the builder.
func (_c *ShopDrawCycleCreate) Mutation() *ShopDrawCycleMutation {
	return _c.mutation
}

// Save creates the ShopDrawCycle in the database.
func (_c *ShopDrawCycleCreate) Save(ctx context.Context) (*ShopDrawCycle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShopDrawCycleCreate) SaveX(ctx context.Context) *ShopDrawCycle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopDrawCycleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopDrawCycleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShopDrawCycleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shopdrawcycle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shopdrawcycle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DrawnCount(); !ok {
		v := shopdrawcycle.DefaultDrawnCount
		_c.mutation.SetDrawnCount(v)
	}
	if _, ok := _c.mutation.DrawnAmount(); !ok {
		v := shopdrawcycle.DefaultDrawnAmount
		_c.mutation.SetDrawnAmount(v)
	}
	if _, ok := _c.mutation.Completed(); !ok {
		v := shopdrawcycle.DefaultCompleted
		_c.mutation.SetCompleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShopDrawCycleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShopDrawCycle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ShopDrawCycle.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ShopDrawCycle.user_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "ShopDrawCycle.product_id"`)}
	}
	if _, ok := _c.mutation.CycleNo(); !ok {
		return &ValidationError{Name: "cycle_no", err: errors.New(`ent: missing required field "ShopDrawCycle.cycle_no"`)}
	}
	if _, ok := _c.mutation.GuaranteeCount(); !ok {
		return &ValidationError{Name: "guarantee_count", err: errors.New(`ent: missing required field "ShopDrawCycle.guarantee_count"`)}
	}
	if _, ok := _c.mutation.TargetAmount(); !ok {
		return &ValidationError{Name: "target_amount", err: errors.New(`ent: missing required field "ShopDrawCycle.target_amount"`)}
	}
	if _, ok := _c.mutation.DrawnCount(); !ok {
		return &ValidationError{Name: "drawn_count", err: errors.New(`ent: missing required field "ShopDrawCycle.drawn_count"`)}
	}
	if _, ok := _c.mutation.DrawnAmount(); !ok {
		return &ValidationError{Name: "drawn_amount", err: errors.New(`ent: missing required field "ShopDrawCycle.drawn_amount"`)}
	}
	if _, ok := _c.mutation.Completed(); !ok {
		return &ValidationError{Name: "completed", err: errors.New(`ent: missing required field "ShopDrawCycle.completed"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ShopDrawCycle.user"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "ShopDrawCycle.product"`)}
	}
	return nil
}

func (_c *ShopDrawCycleCreate) sqlSave(ctx context.Context) (*ShopDrawCycle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShopDrawCycleCreate) createSpec() (*ShopDrawCycle, *sqlgraph.CreateSpec) {
	var (
		_node = &ShopDrawCycle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shopdrawcycle.Table, sqlgraph.NewFieldSpec(shopdrawcycle.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shopdrawcycle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shopdrawcycle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CycleNo(); ok {
		_spec.SetField(shopdrawcycle.FieldCycleNo, field.TypeInt, value)
		_node.CycleNo = value
	}
	if value, ok := _c.mutation.GuaranteeCount(); ok {
		_spec.SetField(shopdrawcycle.FieldGuaranteeCount, field.TypeInt, value)
		_node.GuaranteeCount = value
	}
	if value, ok := _c.mutation.TargetAmount(); ok {
		_spec.SetField(shopdrawcycle.FieldTargetAmount, field.TypeFloat64, value)
		_node.TargetAmount = value
	}
	if value, ok := _c.mutation.RemainingAmounts(); ok {
		_spec.SetField(shopdrawcycle.FieldRemainingAmounts, field.TypeJSON, value)
		_node.RemainingAmounts = value
	}
	if value, ok := _c.mutation.DrawnCount(); ok {
		_spec.SetField(shopdrawcycle.FieldDrawnCount, field.TypeInt, value)
		_node.DrawnCount = value
	}
	if value, ok := _c.mutation.DrawnAmount(); ok {
		_spec.SetField(shopdrawcycle.FieldDrawnAmount, field.TypeFloat64, value)
		_node.DrawnAmount = value
	}
	if value, ok := _c.mutation.Completed(); ok {
		_spec.SetField(shopdrawcycle.FieldCompleted, field.TypeBool, value)
		_node.Completed = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopdrawcycle.UserTable,
			Columns: []string{shopdrawcycle.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shopdrawcycle.ProductTable,
			Columns: []string{shopdrawcycle.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopdrawcycle.OrdersTable,
			Columns: []string{shopdrawcycle.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BalanceLedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shopdrawcycle.BalanceLedgerTable,
			Columns: []string{shopdrawcycle.BalanceLedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shopbalanceledger.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopDrawCycle.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopDrawCycleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopDrawCycleCreate) OnConflict(opts ...sql.ConflictOption) *ShopDrawCycleUpsertOne {
	_c.conflict = opts
	return &ShopDrawCycleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopDrawCycle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopDrawCycleCreate) OnConflictColumns(columns ...string) *ShopDrawCycleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopDrawCycleUpsertOne{
		create: _c,
	}
}

type (
	// ShopDrawCycleUpsertOne is the builder for "upsert"-ing
	//  one ShopDrawCycle node.
	ShopDrawCycleUpsertOne struct {
		create *ShopDrawCycleCreate
	}

	// ShopDrawCycleUpsert is the "OnConflict" setter.
	ShopDrawCycleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopDrawCycleUpsert) SetUpdatedAt(v time.Time) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateUpdatedAt() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ShopDrawCycleUpsert) SetUserID(v int64) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateUserID() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldUserID)
	return u
}

// SetProductID sets the "product_id" field.
func (u *ShopDrawCycleUpsert) SetProductID(v int64) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateProductID() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldProductID)
	return u
}

// SetCycleNo sets the "cycle_no" field.
func (u *ShopDrawCycleUpsert) SetCycleNo(v int) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldCycleNo, v)
	return u
}

// UpdateCycleNo sets the "cycle_no" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateCycleNo() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldCycleNo)
	return u
}

// AddCycleNo adds v to the "cycle_no" field.
func (u *ShopDrawCycleUpsert) AddCycleNo(v int) *ShopDrawCycleUpsert {
	u.Add(shopdrawcycle.FieldCycleNo, v)
	return u
}

// SetGuaranteeCount sets the "guarantee_count" field.
func (u *ShopDrawCycleUpsert) SetGuaranteeCount(v int) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldGuaranteeCount, v)
	return u
}

// UpdateGuaranteeCount sets the "guarantee_count" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateGuaranteeCount() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldGuaranteeCount)
	return u
}

// AddGuaranteeCount adds v to the "guarantee_count" field.
func (u *ShopDrawCycleUpsert) AddGuaranteeCount(v int) *ShopDrawCycleUpsert {
	u.Add(shopdrawcycle.FieldGuaranteeCount, v)
	return u
}

// SetTargetAmount sets the "target_amount" field.
func (u *ShopDrawCycleUpsert) SetTargetAmount(v float64) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldTargetAmount, v)
	return u
}

// UpdateTargetAmount sets the "target_amount" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateTargetAmount() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldTargetAmount)
	return u
}

// AddTargetAmount adds v to the "target_amount" field.
func (u *ShopDrawCycleUpsert) AddTargetAmount(v float64) *ShopDrawCycleUpsert {
	u.Add(shopdrawcycle.FieldTargetAmount, v)
	return u
}

// SetRemainingAmounts sets the "remaining_amounts" field.
func (u *ShopDrawCycleUpsert) SetRemainingAmounts(v []float64) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldRemainingAmounts, v)
	return u
}

// UpdateRemainingAmounts sets the "remaining_amounts" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateRemainingAmounts() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldRemainingAmounts)
	return u
}

// ClearRemainingAmounts clears the value of the "remaining_amounts" field.
func (u *ShopDrawCycleUpsert) ClearRemainingAmounts() *ShopDrawCycleUpsert {
	u.SetNull(shopdrawcycle.FieldRemainingAmounts)
	return u
}

// SetDrawnCount sets the "drawn_count" field.
func (u *ShopDrawCycleUpsert) SetDrawnCount(v int) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldDrawnCount, v)
	return u
}

// UpdateDrawnCount sets the "drawn_count" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateDrawnCount() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldDrawnCount)
	return u
}

// AddDrawnCount adds v to the "drawn_count" field.
func (u *ShopDrawCycleUpsert) AddDrawnCount(v int) *ShopDrawCycleUpsert {
	u.Add(shopdrawcycle.FieldDrawnCount, v)
	return u
}

// SetDrawnAmount sets the "drawn_amount" field.
func (u *ShopDrawCycleUpsert) SetDrawnAmount(v float64) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldDrawnAmount, v)
	return u
}

// UpdateDrawnAmount sets the "drawn_amount" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateDrawnAmount() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldDrawnAmount)
	return u
}

// AddDrawnAmount adds v to the "drawn_amount" field.
func (u *ShopDrawCycleUpsert) AddDrawnAmount(v float64) *ShopDrawCycleUpsert {
	u.Add(shopdrawcycle.FieldDrawnAmount, v)
	return u
}

// SetCompleted sets the "completed" field.
func (u *ShopDrawCycleUpsert) SetCompleted(v bool) *ShopDrawCycleUpsert {
	u.Set(shopdrawcycle.FieldCompleted, v)
	return u
}

// UpdateCompleted sets the "completed" field to the value that was provided on create.
func (u *ShopDrawCycleUpsert) UpdateCompleted() *ShopDrawCycleUpsert {
	u.SetExcluded(shopdrawcycle.FieldCompleted)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ShopDrawCycle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopDrawCycleUpsertOne) UpdateNewValues() *ShopDrawCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(shopdrawcycle.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopDrawCycle.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShopDrawCycleUpsertOne) Ignore() *ShopDrawCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopDrawCycleUpsertOne) DoNothing() *ShopDrawCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopDrawCycleCreate.OnConflict
// documentation for more info.
func (u *ShopDrawCycleUpsertOne) Update(set func(*ShopDrawCycleUpsert)) *ShopDrawCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopDrawCycleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopDrawCycleUpsertOne) SetUpdatedAt(v time.Time) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateUpdatedAt() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ShopDrawCycleUpsertOne) SetUserID(v int64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateUserID() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *ShopDrawCycleUpsertOne) SetProductID(v int64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateProductID() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateProductID()
	})
}

// SetCycleNo sets the "cycle_no" field.
func (u *ShopDrawCycleUpsertOne) SetCycleNo(v int) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetCycleNo(v)
	})
}

// AddCycleNo adds v to the "cycle_no" field.
func (u *ShopDrawCycleUpsertOne) AddCycleNo(v int) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddCycleNo(v)
	})
}

// UpdateCycleNo sets the "cycle_no" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateCycleNo() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateCycleNo()
	})
}

// SetGuaranteeCount sets the "guarantee_count" field.
func (u *ShopDrawCycleUpsertOne) SetGuaranteeCount(v int) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetGuaranteeCount(v)
	})
}

// AddGuaranteeCount adds v to the "guarantee_count" field.
func (u *ShopDrawCycleUpsertOne) AddGuaranteeCount(v int) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddGuaranteeCount(v)
	})
}

// UpdateGuaranteeCount sets the "guarantee_count" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateGuaranteeCount() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateGuaranteeCount()
	})
}

// SetTargetAmount sets the "target_amount" field.
func (u *ShopDrawCycleUpsertOne) SetTargetAmount(v float64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetTargetAmount(v)
	})
}

// AddTargetAmount adds v to the "target_amount" field.
func (u *ShopDrawCycleUpsertOne) AddTargetAmount(v float64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddTargetAmount(v)
	})
}

// UpdateTargetAmount sets the "target_amount" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateTargetAmount() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateTargetAmount()
	})
}

// SetRemainingAmounts sets the "remaining_amounts" field.
func (u *ShopDrawCycleUpsertOne) SetRemainingAmounts(v []float64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetRemainingAmounts(v)
	})
}

// UpdateRemainingAmounts sets the "remaining_amounts" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateRemainingAmounts() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateRemainingAmounts()
	})
}

// ClearRemainingAmounts clears the value of the "remaining_amounts" field.
func (u *ShopDrawCycleUpsertOne) ClearRemainingAmounts() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.ClearRemainingAmounts()
	})
}

// SetDrawnCount sets the "drawn_count" field.
func (u *ShopDrawCycleUpsertOne) SetDrawnCount(v int) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetDrawnCount(v)
	})
}

// AddDrawnCount adds v to the "drawn_count" field.
func (u *ShopDrawCycleUpsertOne) AddDrawnCount(v int) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddDrawnCount(v)
	})
}

// UpdateDrawnCount sets the "drawn_count" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateDrawnCount() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateDrawnCount()
	})
}

// SetDrawnAmount sets the "drawn_amount" field.
func (u *ShopDrawCycleUpsertOne) SetDrawnAmount(v float64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetDrawnAmount(v)
	})
}

// AddDrawnAmount adds v to the "drawn_amount" field.
func (u *ShopDrawCycleUpsertOne) AddDrawnAmount(v float64) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddDrawnAmount(v)
	})
}

// UpdateDrawnAmount sets the "drawn_amount" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateDrawnAmount() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateDrawnAmount()
	})
}

// SetCompleted sets the "completed" field.
func (u *ShopDrawCycleUpsertOne) SetCompleted(v bool) *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetCompleted(v)
	})
}

// UpdateCompleted sets the "completed" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertOne) UpdateCompleted() *ShopDrawCycleUpsertOne {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateCompleted()
	})
}

// Exec executes the query.
func (u *ShopDrawCycleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopDrawCycleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopDrawCycleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShopDrawCycleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShopDrawCycleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShopDrawCycleCreateBulk is the builder for creating many ShopDrawCycle entities in bulk.
type ShopDrawCycleCreateBulk struct {
	config
	err      error
	builders []*ShopDrawCycleCreate
	conflict []sql.ConflictOption
}

// Save creates the ShopDrawCycle entities in the database.
func (_c *ShopDrawCycleCreateBulk) Save(ctx context.Context) ([]*ShopDrawCycle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShopDrawCycle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShopDrawCycleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShopDrawCycleCreateBulk) SaveX(ctx context.Context) []*ShopDrawCycle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopDrawCycleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopDrawCycleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopDrawCycle.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopDrawCycleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopDrawCycleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShopDrawCycleUpsertBulk {
	_c.conflict = opts
	return &ShopDrawCycleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopDrawCycle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopDrawCycleCreateBulk) OnConflictColumns(columns ...string) *ShopDrawCycleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopDrawCycleUpsertBulk{
		create: _c,
	}
}

// ShopDrawCycleUpsertBulk is the builder for "upsert"-ing
// a bulk of ShopDrawCycle nodes.
type ShopDrawCycleUpsertBulk struct {
	create *ShopDrawCycleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ShopDrawCycle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopDrawCycleUpsertBulk) UpdateNewValues() *ShopDrawCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(shopdrawcycle.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopDrawCycle.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShopDrawCycleUpsertBulk) Ignore() *ShopDrawCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopDrawCycleUpsertBulk) DoNothing() *ShopDrawCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopDrawCycleCreateBulk.OnConflict
// documentation for more info.
func (u *ShopDrawCycleUpsertBulk) Update(set func(*ShopDrawCycleUpsert)) *ShopDrawCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopDrawCycleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShopDrawCycleUpsertBulk) SetUpdatedAt(v time.Time) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateUpdatedAt() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ShopDrawCycleUpsertBulk) SetUserID(v int64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateUserID() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *ShopDrawCycleUpsertBulk) SetProductID(v int64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateProductID() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateProductID()
	})
}

// SetCycleNo sets the "cycle_no" field.
func (u *ShopDrawCycleUpsertBulk) SetCycleNo(v int) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetCycleNo(v)
	})
}

// AddCycleNo adds v to the "cycle_no" field.
func (u *ShopDrawCycleUpsertBulk) AddCycleNo(v int) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddCycleNo(v)
	})
}

// UpdateCycleNo sets the "cycle_no" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateCycleNo() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateCycleNo()
	})
}

// SetGuaranteeCount sets the "guarantee_count" field.
func (u *ShopDrawCycleUpsertBulk) SetGuaranteeCount(v int) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetGuaranteeCount(v)
	})
}

// AddGuaranteeCount adds v to the "guarantee_count" field.
func (u *ShopDrawCycleUpsertBulk) AddGuaranteeCount(v int) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddGuaranteeCount(v)
	})
}

// UpdateGuaranteeCount sets the "guarantee_count" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateGuaranteeCount() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateGuaranteeCount()
	})
}

// SetTargetAmount sets the "target_amount" field.
func (u *ShopDrawCycleUpsertBulk) SetTargetAmount(v float64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetTargetAmount(v)
	})
}

// AddTargetAmount adds v to the "target_amount" field.
func (u *ShopDrawCycleUpsertBulk) AddTargetAmount(v float64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddTargetAmount(v)
	})
}

// UpdateTargetAmount sets the "target_amount" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateTargetAmount() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateTargetAmount()
	})
}

// SetRemainingAmounts sets the "remaining_amounts" field.
func (u *ShopDrawCycleUpsertBulk) SetRemainingAmounts(v []float64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetRemainingAmounts(v)
	})
}

// UpdateRemainingAmounts sets the "remaining_amounts" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateRemainingAmounts() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateRemainingAmounts()
	})
}

// ClearRemainingAmounts clears the value of the "remaining_amounts" field.
func (u *ShopDrawCycleUpsertBulk) ClearRemainingAmounts() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.ClearRemainingAmounts()
	})
}

// SetDrawnCount sets the "drawn_count" field.
func (u *ShopDrawCycleUpsertBulk) SetDrawnCount(v int) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetDrawnCount(v)
	})
}

// AddDrawnCount adds v to the "drawn_count" field.
func (u *ShopDrawCycleUpsertBulk) AddDrawnCount(v int) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddDrawnCount(v)
	})
}

// UpdateDrawnCount sets the "drawn_count" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateDrawnCount() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateDrawnCount()
	})
}

// SetDrawnAmount sets the "drawn_amount" field.
func (u *ShopDrawCycleUpsertBulk) SetDrawnAmount(v float64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetDrawnAmount(v)
	})
}

// AddDrawnAmount adds v to the "drawn_amount" field.
func (u *ShopDrawCycleUpsertBulk) AddDrawnAmount(v float64) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.AddDrawnAmount(v)
	})
}

// UpdateDrawnAmount sets the "drawn_amount" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateDrawnAmount() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateDrawnAmount()
	})
}

// SetCompleted sets the "completed" field.
func (u *ShopDrawCycleUpsertBulk) SetCompleted(v bool) *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.SetCompleted(v)
	})
}

// UpdateCompleted sets the "completed" field to the value that was provided on create.
func (u *ShopDrawCycleUpsertBulk) UpdateCompleted() *ShopDrawCycleUpsertBulk {
	return u.Update(func(s *ShopDrawCycleUpsert) {
		s.UpdateCompleted()
	})
}

// Exec executes the query.
func (u *ShopDrawCycleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShopDrawCycleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopDrawCycleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopDrawCycleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
