// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ikik-api/ent/shopcategory"
	"ikik-api/ent/shopproduct"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ShopProduct is the model entity for the ShopProduct schema.
type ShopProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID *int64 `json:"category_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CoverURL holds the value of the "cover_url" field.
	CoverURL *string `json:"cover_url,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// OriginalPrice holds the value of the "original_price" field.
	OriginalPrice *float64 `json:"original_price,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// MinPurchase holds the value of the "min_purchase" field.
	MinPurchase int `json:"min_purchase,omitempty"`
	// MaxPurchase holds the value of the "max_purchase" field.
	MaxPurchase int `json:"max_purchase,omitempty"`
	// AutoDelivery holds the value of the "auto_delivery" field.
	AutoDelivery bool `json:"auto_delivery,omitempty"`
	// ProductType holds the value of the "product_type" field.
	ProductType string `json:"product_type,omitempty"`
	// BalanceOnly holds the value of the "balance_only" field.
	BalanceOnly bool `json:"balance_only,omitempty"`
	// AllowBalancePayment holds the value of the "allow_balance_payment" field.
	AllowBalancePayment bool `json:"allow_balance_payment,omitempty"`
	// AllowPointsPayment holds the value of the "allow_points_payment" field.
	AllowPointsPayment bool `json:"allow_points_payment,omitempty"`
	// AllowPlatformPayment holds the value of the "allow_platform_payment" field.
	AllowPlatformPayment bool `json:"allow_platform_payment,omitempty"`
	// DrawEnabled holds the value of the "draw_enabled" field.
	DrawEnabled bool `json:"draw_enabled,omitempty"`
	// DrawMinAmount holds the value of the "draw_min_amount" field.
	DrawMinAmount float64 `json:"draw_min_amount,omitempty"`
	// DrawMaxAmount holds the value of the "draw_max_amount" field.
	DrawMaxAmount float64 `json:"draw_max_amount,omitempty"`
	// DrawGuaranteeCount holds the value of the "draw_guarantee_count" field.
	DrawGuaranteeCount int `json:"draw_guarantee_count,omitempty"`
	// DrawReturnRate holds the value of the "draw_return_rate" field.
	DrawReturnRate float64 `json:"draw_return_rate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShopProductQuery when eager-loading is set.
	Edges        ShopProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShopProductEdges holds the relations/edges for other nodes in the graph.
type ShopProductEdges struct {
	// Category holds the value of the category edge.
	Category *ShopCategory `json:"category,omitempty"`
	// CardKeys holds the value of the card_keys edge.
	CardKeys []*ShopCardKey `json:"card_keys,omitempty"`
	// Orders holds the value of the orders edge.
	Orders []*ShopOrder `json:"orders,omitempty"`
	// DrawCycles holds the value of the draw_cycles edge.
	DrawCycles []*ShopDrawCycle `json:"draw_cycles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShopProductEdges) CategoryOrErr() (*ShopCategory, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shopcategory.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// CardKeysOrErr returns the CardKeys value or an error if the edge
// was not loaded in eager-loading.
func (e ShopProductEdges) CardKeysOrErr() ([]*ShopCardKey, error) {
	if e.loadedTypes[1] {
		return e.CardKeys, nil
	}
	return nil, &NotLoadedError{edge: "card_keys"}
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e ShopProductEdges) OrdersOrErr() ([]*ShopOrder, error) {
	if e.loadedTypes[2] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// DrawCyclesOrErr returns the DrawCycles value or an error if the edge
// was not loaded in eager-loading.
func (e ShopProductEdges) DrawCyclesOrErr() ([]*ShopDrawCycle, error) {
	if e.loadedTypes[3] {
		return e.DrawCycles, nil
	}
	return nil, &NotLoadedError{edge: "draw_cycles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShopProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shopproduct.FieldEnabled, shopproduct.FieldAutoDelivery, shopproduct.FieldBalanceOnly, shopproduct.FieldAllowBalancePayment, shopproduct.FieldAllowPointsPayment, shopproduct.FieldAllowPlatformPayment, shopproduct.FieldDrawEnabled:
			values[i] = new(sql.NullBool)
		case shopproduct.FieldPrice, shopproduct.FieldOriginalPrice, shopproduct.FieldDrawMinAmount, shopproduct.FieldDrawMaxAmount, shopproduct.FieldDrawReturnRate:
			values[i] = new(sql.NullFloat64)
		case shopproduct.FieldID, shopproduct.FieldCategoryID, shopproduct.FieldSortOrder, shopproduct.FieldMinPurchase, shopproduct.FieldMaxPurchase, shopproduct.FieldDrawGuaranteeCount:
			values[i] = new(sql.NullInt64)
		case shopproduct.FieldName, shopproduct.FieldCoverURL, shopproduct.FieldDescription, shopproduct.FieldProductType:
			values[i] = new(sql.NullString)
		case shopproduct.FieldCreatedAt, shopproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShopProduct fields.
func (_m *ShopProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shopproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case shopproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shopproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case shopproduct.FieldCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = new(int64)
				*_m.CategoryID = value.Int64
			}
		case shopproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case shopproduct.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = new(string)
				*_m.CoverURL = value.String
			}
		case shopproduct.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case shopproduct.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case shopproduct.FieldOriginalPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field original_price", values[i])
			} else if value.Valid {
				_m.OriginalPrice = new(float64)
				*_m.OriginalPrice = value.Float64
			}
		case shopproduct.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case shopproduct.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case shopproduct.FieldMinPurchase:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_purchase", values[i])
			} else if value.Valid {
				_m.MinPurchase = int(value.Int64)
			}
		case shopproduct.FieldMaxPurchase:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_purchase", values[i])
			} else if value.Valid {
				_m.MaxPurchase = int(value.Int64)
			}
		case shopproduct.FieldAutoDelivery:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_delivery", values[i])
			} else if value.Valid {
				_m.AutoDelivery = value.Bool
			}
		case shopproduct.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = value.String
			}
		case shopproduct.FieldBalanceOnly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field balance_only", values[i])
			} else if value.Valid {
				_m.BalanceOnly = value.Bool
			}
		case shopproduct.FieldAllowBalancePayment:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_balance_payment", values[i])
			} else if value.Valid {
				_m.AllowBalancePayment = value.Bool
			}
		case shopproduct.FieldAllowPointsPayment:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_points_payment", values[i])
			} else if value.Valid {
				_m.AllowPointsPayment = value.Bool
			}
		case shopproduct.FieldAllowPlatformPayment:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_platform_payment", values[i])
			} else if value.Valid {
				_m.AllowPlatformPayment = value.Bool
			}
		case shopproduct.FieldDrawEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field draw_enabled", values[i])
			} else if value.Valid {
				_m.DrawEnabled = value.Bool
			}
		case shopproduct.FieldDrawMinAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_min_amount", values[i])
			} else if value.Valid {
				_m.DrawMinAmount = value.Float64
			}
		case shopproduct.FieldDrawMaxAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_max_amount", values[i])
			} else if value.Valid {
				_m.DrawMaxAmount = value.Float64
			}
		case shopproduct.FieldDrawGuaranteeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_guarantee_count", values[i])
			} else if value.Valid {
				_m.DrawGuaranteeCount = int(value.Int64)
			}
		case shopproduct.FieldDrawReturnRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_return_rate", values[i])
			} else if value.Valid {
				_m.DrawReturnRate = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShopProduct.
// This includes values selected through modifiers, order, etc.
func (_m *ShopProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the ShopProduct entity.
func (_m *ShopProduct) QueryCategory() *ShopCategoryQuery {
	return NewShopProductClient(_m.config).QueryCategory(_m)
}

// QueryCardKeys queries the "card_keys" edge of the ShopProduct entity.
func (_m *ShopProduct) QueryCardKeys() *ShopCardKeyQuery {
	return NewShopProductClient(_m.config).QueryCardKeys(_m)
}

// QueryOrders queries the "orders" edge of the ShopProduct entity.
func (_m *ShopProduct) QueryOrders() *ShopOrderQuery {
	return NewShopProductClient(_m.config).QueryOrders(_m)
}

// QueryDrawCycles queries the "draw_cycles" edge of the ShopProduct entity.
func (_m *ShopProduct) QueryDrawCycles() *ShopDrawCycleQuery {
	return NewShopProductClient(_m.config).QueryDrawCycles(_m)
}

// Update returns a builder for updating this ShopProduct.
// Note that you need to call ShopProduct.Unwrap() before calling this method if this ShopProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShopProduct) Update() *ShopProductUpdateOne {
	return NewShopProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShopProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShopProduct) Unwrap() *ShopProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShopProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShopProduct) String() string {
	var builder strings.Builder
	builder.WriteString("ShopProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CategoryID; v != nil {
		builder.WriteString("category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.CoverURL; v != nil {
		builder.WriteString("cover_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	if v := _m.OriginalPrice; v != nil {
		builder.WriteString("original_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("min_purchase=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinPurchase))
	builder.WriteString(", ")
	builder.WriteString("max_purchase=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxPurchase))
	builder.WriteString(", ")
	builder.WriteString("auto_delivery=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoDelivery))
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(_m.ProductType)
	builder.WriteString(", ")
	builder.WriteString("balance_only=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceOnly))
	builder.WriteString(", ")
	builder.WriteString("allow_balance_payment=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowBalancePayment))
	builder.WriteString(", ")
	builder.WriteString("allow_points_payment=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowPointsPayment))
	builder.WriteString(", ")
	builder.WriteString("allow_platform_payment=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowPlatformPayment))
	builder.WriteString(", ")
	builder.WriteString("draw_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrawEnabled))
	builder.WriteString(", ")
	builder.WriteString("draw_min_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrawMinAmount))
	builder.WriteString(", ")
	builder.WriteString("draw_max_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrawMaxAmount))
	builder.WriteString(", ")
	builder.WriteString("draw_guarantee_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrawGuaranteeCount))
	builder.WriteString(", ")
	builder.WriteString("draw_return_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrawReturnRate))
	builder.WriteByte(')')
	return builder.String()
}

// ShopProducts is a parsable slice of ShopProduct.
type ShopProducts []*ShopProduct
