// Code generated by ent, DO NOT EDIT.

package apikeygrouproute

import (
	"ikik-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldGroupID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldPriority, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldWeight, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldEnabled, v))
}

// CooldownSeconds applies equality check predicate on the "cooldown_seconds" field. It's identical to CooldownSecondsEQ.
func CooldownSeconds(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldCooldownSeconds, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLTE(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldGroupID, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLTE(FieldPriority, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLTE(FieldWeight, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldEnabled, v))
}

// CooldownSecondsEQ applies the EQ predicate on the "cooldown_seconds" field.
func CooldownSecondsEQ(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldEQ(FieldCooldownSeconds, v))
}

// CooldownSecondsNEQ applies the NEQ predicate on the "cooldown_seconds" field.
func CooldownSecondsNEQ(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNEQ(FieldCooldownSeconds, v))
}

// CooldownSecondsIn applies the In predicate on the "cooldown_seconds" field.
func CooldownSecondsIn(vs ...int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldIn(FieldCooldownSeconds, vs...))
}

// CooldownSecondsNotIn applies the NotIn predicate on the "cooldown_seconds" field.
func CooldownSecondsNotIn(vs ...int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldNotIn(FieldCooldownSeconds, vs...))
}

// CooldownSecondsGT applies the GT predicate on the "cooldown_seconds" field.
func CooldownSecondsGT(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGT(FieldCooldownSeconds, v))
}

// CooldownSecondsGTE applies the GTE predicate on the "cooldown_seconds" field.
func CooldownSecondsGTE(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldGTE(FieldCooldownSeconds, v))
}

// CooldownSecondsLT applies the LT predicate on the "cooldown_seconds" field.
func CooldownSecondsLT(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLT(FieldCooldownSeconds, v))
}

// CooldownSecondsLTE applies the LTE predicate on the "cooldown_seconds" field.
func CooldownSecondsLTE(v int) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.FieldLTE(FieldCooldownSeconds, v))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyGroupRoute) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyGroupRoute) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyGroupRoute) predicate.APIKeyGroupRoute {
	return predicate.APIKeyGroupRoute(sql.NotPredicates(p))
}
