ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root

COPY --chown=ikik-api:ikik-api backend/bin/ikik-api-linux-amd64 /app/ikik-api
COPY --chown=ikik-api:ikik-api backend/resources /app/resources

RUN chmod 0755 /app/ikik-api
