// Code generated by ent, DO NOT EDIT.

package emailbroadcast

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the emailbroadcast type in the database.
	Label = "email_broadcast"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldBodyFormat holds the string denoting the body_format field in the database.
	FieldBodyFormat = "body_format"
	// FieldRecipientsMode holds the string denoting the recipients_mode field in the database.
	FieldRecipientsMode = "recipients_mode"
	// FieldRecipientUserIds holds the string denoting the recipient_user_ids field in the database.
	FieldRecipientUserIds = "recipient_user_ids"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotalCount holds the string denoting the total_count field in the database.
	FieldTotalCount = "total_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldFailedCount holds the string denoting the failed_count field in the database.
	FieldFailedCount = "failed_count"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the emailbroadcast in the database.
	Table = "email_broadcasts"
)

// Columns holds all SQL columns for emailbroadcast fields.
var Columns = []string{
	FieldID,
	FieldSubject,
	FieldBody,
	FieldBodyFormat,
	FieldRecipientsMode,
	FieldRecipientUserIds,
	FieldStatus,
	FieldTotalCount,
	FieldSuccessCount,
	FieldFailedCount,
	FieldErrorMessage,
	FieldCreatedBy,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
	// DefaultBodyFormat holds the default value on creation for the "body_format" field.
	DefaultBodyFormat string
	// BodyFormatValidator is a validator for the "body_format" field. It is called by the builders before save.
	BodyFormatValidator func(string) error
	// DefaultRecipientsMode holds the default value on creation for the "recipients_mode" field.
	DefaultRecipientsMode string
	// RecipientsModeValidator is a validator for the "recipients_mode" field. It is called by the builders before save.
	RecipientsModeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTotalCount holds the default value on creation for the "total_count" field.
	DefaultTotalCount int
	// TotalCountValidator is a validator for the "total_count" field. It is called by the builders before save.
	TotalCountValidator func(int) error
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int
	// SuccessCountValidator is a validator for the "success_count" field. It is called by the builders before save.
	SuccessCountValidator func(int) error
	// DefaultFailedCount holds the default value on creation for the "failed_count" field.
	DefaultFailedCount int
	// FailedCountValidator is a validator for the "failed_count" field. It is called by the builders before save.
	FailedCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the EmailBroadcast queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByBodyFormat orders the results by the body_format field.
func ByBodyFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBodyFormat, opts...).ToFunc()
}

// ByRecipientsMode orders the results by the recipients_mode field.
func ByRecipientsMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientsMode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotalCount orders the results by the total_count field.
func ByTotalCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByFailedCount orders the results by the failed_count field.
func ByFailedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedCount, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
