import type { Ref } from 'vue'

const zh = {
  searchPlaceholder: '搜索任务名称',
  reset: '重置',
  refresh: '刷新',
  guide: '使用说明',
  createJob: '创建批量任务',
  selectedJobs: '已选择 {count} 个任务',
  downloadSelected: '下载选中',
  deleteRecord: '删除记录',
  collapseChildren: '收起子任务',
  expandChildren: '展开 {count} 个子任务',
  childCount: '{count} 子任务',
  childJob: '子任务',
  notRecorded: '未记录',
  totalCount: '共 {count}',
  notDownloaded: '未下载',
  viewDetails: '查看详情',
  view: '查看',
  downloadZip: '下载 ZIP',
  download: '下载',
  moreActions: '更多操作',
  more: '更多',
  emptyTitle: '暂无批量任务',
  emptyHint: '点击右上角创建批量任务',
  pageNumber: '第 {page} 页',
  pageItemCount: '本页 {count} 条',
  perPage: '每页',
  previousPage: '上一页',
  nextPage: '下一页',
  retryFailed: '重试失败项',
  fullPrompt: '完整 Prompt',
  copy: '复制',
  jobDetails: '任务详情',
  status: '状态',
  summaryResult: '汇总结果',
  result: '结果',
  cost: '费用',
  downloadStatus: '下载状态',
  details: '明细',
  preview: '预览',
  zoomPreview: '放大压缩预览 {id}',
  reloadPreview: '重新加载压缩预览',
  loadPreview: '加载压缩预览',
  unavailablePreview: '不可预览',
  noImage: '无图片',
  loadingDetails: '正在加载明细...',
  noDetails: '暂无明细',
  pendingDetailsHint: '排队或生成中的任务会先显示已提交的 prompt，结果整理完成后会更新图片状态',
  cancelJob: '取消任务',
  imagePreview: '图片预览',
  previewCacheHint: '当前显示的是浏览器本地缓存的压缩缩略图，清晰度会有影响；需要查看原图请下载 ZIP',
  taskName: '任务名称',
  taskNamePlaceholder: '不填写则默认使用当前时间',
  loadingApiKeys: '加载 API Key 中...',
  selectGeminiKey: '请选择 Gemini API Key',
  noApiKeysHint: '当前没有可用于批量生图的 Gemini API Key。请先创建并绑定已开启批量生图的 Gemini 分组',
  model: '模型',
  imageSize: '图片尺寸',
  fixed1kHint: '当前批量任务固定按 1K 图片提交',
  outputFormat: '输出格式',
  expectedOutput: '预计生成',
  outputSummary: '{images} 张 / {prompts} 条',
  addedPrompts: '已添加 {count} 条',
  promptPlaceholder: '粘贴 prompt，添加后进入下方列表',
  customIdPlaceholder: 'Custom ID 可选',
  outputCountTitle: '每条生成张数',
  imagesCount: '{count} 张',
  referenceImage: '参考图',
  add: '添加',
  removeReferenceImage: '移除参考图',
  limitsHint: '每条最多 {perItem} 张，整组最多 {perJob} 张；当前模型每条最多 {references} 张参考图，参考图按生成张数重复消耗输入 token',
  referenceCount: '{count} 参考图',
  delete: '删除',
  noPrompts: '还没有添加 prompt',
  cancelBillingHint: '取消任务会请求上游取消；已被系统索引为成功的图片仍会按成功项结算扣费，其余冻结金额会释放',
  submittingHint: '正在创建上游批量任务，通常需要几秒，请不要重复提交',
  cancel: '取消',
  submitting: '提交中...',
  submitJob: '提交任务',
  guideTitle: '批量生图使用说明',
  guideUsageTitle: '当前界面如何使用',
  guideStep1: '1. 选择已开启批量生图的 Gemini API Key，模型列表会按该 Key 所属分组可用模型展示',
  guideStep2: '2. 任务名称可以留空，提交时会自动使用当前时间；Prompt 需要一条条添加到列表里，每条 Prompt 可附参考图，也可以设置重复生成张数',
  guideStep3: '3. 提交后任务会先排队，明细会展示已提交的 Prompt；图片预览默认不加载，点击明细里的预览按钮才会加载单张图',
  guideStep4: '4. 完成后可以下载 ZIP；部分失败时，更多菜单里可以只重试失败项。当前结算仍按成功输出图张数计算，不单独对参考图加价',
  agentGuideTitle: '给 Codex 的 Skill 说明',
  agentGuideHint: '用于告诉 Codex 如何代替用户整理 prompt、提交任务和下载结果',
  close: '关闭',
  copyGuide: '复制说明'
} as const

const en: Record<keyof typeof zh, string> = {
  searchPlaceholder: 'Search job names',
  reset: 'Reset',
  refresh: 'Refresh',
  guide: 'Guide',
  createJob: 'Create batch job',
  selectedJobs: '{count} jobs selected',
  downloadSelected: 'Download selected',
  deleteRecord: 'Delete records',
  collapseChildren: 'Collapse child jobs',
  expandChildren: 'Expand {count} child jobs',
  childCount: '{count} child jobs',
  childJob: 'Child job',
  notRecorded: 'Not recorded',
  totalCount: '{count} total',
  notDownloaded: 'Not downloaded',
  viewDetails: 'View details',
  view: 'View',
  downloadZip: 'Download ZIP',
  download: 'Download',
  moreActions: 'More actions',
  more: 'More',
  emptyTitle: 'No batch jobs',
  emptyHint: 'Create a batch job from the top right',
  pageNumber: 'Page {page}',
  pageItemCount: '{count} on this page',
  perPage: 'Per page',
  previousPage: 'Previous',
  nextPage: 'Next',
  retryFailed: 'Retry failed items',
  fullPrompt: 'Full prompt',
  copy: 'Copy',
  jobDetails: 'Job details',
  status: 'Status',
  summaryResult: 'Combined result',
  result: 'Result',
  cost: 'Cost',
  downloadStatus: 'Download status',
  details: 'Details',
  preview: 'Preview',
  zoomPreview: 'Open compressed preview {id}',
  reloadPreview: 'Reload compressed preview',
  loadPreview: 'Load compressed preview',
  unavailablePreview: 'Preview unavailable',
  noImage: 'No image',
  loadingDetails: 'Loading details...',
  noDetails: 'No details',
  pendingDetailsHint: 'Queued and running jobs show submitted prompts first. Image status updates after results are processed',
  cancelJob: 'Cancel job',
  imagePreview: 'Image preview',
  previewCacheHint: 'This is a compressed thumbnail cached in your browser. Download the ZIP to view the original image',
  taskName: 'Job name',
  taskNamePlaceholder: 'Uses the current time when left blank',
  loadingApiKeys: 'Loading API keys...',
  selectGeminiKey: 'Select a Gemini API key',
  noApiKeysHint: 'No Gemini API key is available for batch image generation. Create a key bound to an enabled Gemini group first',
  model: 'Model',
  imageSize: 'Image size',
  fixed1kHint: 'Batch jobs currently submit 1K images',
  outputFormat: 'Output format',
  expectedOutput: 'Expected output',
  outputSummary: '{images} images / {prompts} prompts',
  addedPrompts: '{count} prompts added',
  promptPlaceholder: 'Paste a prompt and add it to the list below',
  customIdPlaceholder: 'Custom ID (optional)',
  outputCountTitle: 'Images per prompt',
  imagesCount: '{count} images',
  referenceImage: 'Reference images',
  add: 'Add',
  removeReferenceImage: 'Remove reference image',
  limitsHint: 'Up to {perItem} images per prompt and {perJob} per job. This model supports {references} reference images per prompt; input tokens scale with output count',
  referenceCount: '{count} reference images',
  delete: 'Delete',
  noPrompts: 'No prompts added',
  cancelBillingHint: 'Cancellation is sent upstream. Successfully indexed images are still billed and the remaining hold is released',
  submittingHint: 'Creating the upstream batch job. This usually takes a few seconds; do not submit twice',
  cancel: 'Cancel',
  submitting: 'Submitting...',
  submitJob: 'Submit job',
  guideTitle: 'Batch image guide',
  guideUsageTitle: 'How to use this page',
  guideStep1: '1. Select a Gemini API key with batch images enabled. Models are loaded from the key\'s group',
  guideStep2: '2. The job name is optional. Add prompts one at a time; each prompt can include reference images and an output count',
  guideStep3: '3. Jobs queue after submission. Details show submitted prompts, and previews load only when requested',
  guideStep4: '4. Download the ZIP after completion. Failed items can be retried from More. Billing is based on successful output images',
  agentGuideTitle: 'Codex Skill instructions',
  agentGuideHint: 'Instructions for preparing prompts, submitting jobs, and downloading results',
  close: 'Close',
  copyGuide: 'Copy guide'
}

export type BatchImageGuideUiTextKey = keyof typeof zh

export function createBatchImageGuideUiText(locale: Ref<string>) {
  return (key: BatchImageGuideUiTextKey, params: Record<string, string | number> = {}): string => {
    const dictionary = String(locale.value || '').toLowerCase().startsWith('zh') ? zh : en
    return dictionary[key].replace(/\{(\w+)\}/g, (match, name: string) =>
      Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match
    )
  }
}
