// Code generated by ent, DO NOT EDIT.

package shoporder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the shoporder type in the database.
	Label = "shop_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldProductCoverURL holds the string denoting the product_cover_url field in the database.
	FieldProductCoverURL = "product_cover_url"
	// FieldProductDescription holds the string denoting the product_description field in the database.
	FieldProductDescription = "product_description"
	// FieldProductType holds the string denoting the product_type field in the database.
	FieldProductType = "product_type"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldPointsAmount holds the string denoting the points_amount field in the database.
	FieldPointsAmount = "points_amount"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeliveredCards holds the string denoting the delivered_cards field in the database.
	FieldDeliveredCards = "delivered_cards"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// FieldFailedReason holds the string denoting the failed_reason field in the database.
	FieldFailedReason = "failed_reason"
	// FieldDrawRewardAmount holds the string denoting the draw_reward_amount field in the database.
	FieldDrawRewardAmount = "draw_reward_amount"
	// FieldDrawCycleID holds the string denoting the draw_cycle_id field in the database.
	FieldDrawCycleID = "draw_cycle_id"
	// FieldDrawCycleIndex holds the string denoting the draw_cycle_index field in the database.
	FieldDrawCycleIndex = "draw_cycle_index"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeDrawCycle holds the string denoting the draw_cycle edge name in mutations.
	EdgeDrawCycle = "draw_cycle"
	// EdgeBalanceLedger holds the string denoting the balance_ledger edge name in mutations.
	EdgeBalanceLedger = "balance_ledger"
	// EdgeCardKeys holds the string denoting the card_keys edge name in mutations.
	EdgeCardKeys = "card_keys"
	// Table holds the table name of the shoporder in the database.
	Table = "shop_orders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "shop_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "shop_orders"
	// ProductInverseTable is the table name for the ShopProduct entity.
	// It exists in this package in order to avoid circular dependency with the "shopproduct" package.
	ProductInverseTable = "shop_products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// DrawCycleTable is the table that holds the draw_cycle relation/edge.
	DrawCycleTable = "shop_orders"
	// DrawCycleInverseTable is the table name for the ShopDrawCycle entity.
	// It exists in this package in order to avoid circular dependency with the "shopdrawcycle" package.
	DrawCycleInverseTable = "shop_draw_cycles"
	// DrawCycleColumn is the table column denoting the draw_cycle relation/edge.
	DrawCycleColumn = "draw_cycle_id"
	// BalanceLedgerTable is the table that holds the balance_ledger relation/edge.
	BalanceLedgerTable = "shop_balance_ledger"
	// BalanceLedgerInverseTable is the table name for the ShopBalanceLedger entity.
	// It exists in this package in order to avoid circular dependency with the "shopbalanceledger" package.
	BalanceLedgerInverseTable = "shop_balance_ledger"
	// BalanceLedgerColumn is the table column denoting the balance_ledger relation/edge.
	BalanceLedgerColumn = "shop_order_id"
	// CardKeysTable is the table that holds the card_keys relation/edge.
	CardKeysTable = "shop_card_keys"
	// CardKeysInverseTable is the table name for the ShopCardKey entity.
	// It exists in this package in order to avoid circular dependency with the "shopcardkey" package.
	CardKeysInverseTable = "shop_card_keys"
	// CardKeysColumn is the table column denoting the card_keys relation/edge.
	CardKeysColumn = "order_id"
)

// Columns holds all SQL columns for shoporder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrderNo,
	FieldUserID,
	FieldProductID,
	FieldProductName,
	FieldProductCoverURL,
	FieldProductDescription,
	FieldProductType,
	FieldUnitPrice,
	FieldQuantity,
	FieldTotalAmount,
	FieldPointsAmount,
	FieldPaymentMethod,
	FieldPaymentOrderID,
	FieldStatus,
	FieldDeliveredCards,
	FieldPaidAt,
	FieldCompletedAt,
	FieldCancelledAt,
	FieldFailedReason,
	FieldDrawRewardAmount,
	FieldDrawCycleID,
	FieldDrawCycleIndex,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	ProductNameValidator func(string) error
	// DefaultProductType holds the default value on creation for the "product_type" field.
	DefaultProductType string
	// ProductTypeValidator is a validator for the "product_type" field. It is called by the builders before save.
	ProductTypeValidator func(string) error
	// DefaultPointsAmount holds the default value on creation for the "points_amount" field.
	DefaultPointsAmount float64
	// PaymentMethodValidator is a validator for the "payment_method" field. It is called by the builders before save.
	PaymentMethodValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the ShopOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByProductName orders the results by the product_name field.
func ByProductName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductName, opts...).ToFunc()
}

// ByProductCoverURL orders the results by the product_cover_url field.
func ByProductCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductCoverURL, opts...).ToFunc()
}

// ByProductDescription orders the results by the product_description field.
func ByProductDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductDescription, opts...).ToFunc()
}

// ByProductType orders the results by the product_type field.
func ByProductType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductType, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByPointsAmount orders the results by the points_amount field.
func ByPointsAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPointsAmount, opts...).ToFunc()
}

// ByPaymentMethod orders the results by the payment_method field.
func ByPaymentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentMethod, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}

// ByFailedReason orders the results by the failed_reason field.
func ByFailedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedReason, opts...).ToFunc()
}

// ByDrawRewardAmount orders the results by the draw_reward_amount field.
func ByDrawRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrawRewardAmount, opts...).ToFunc()
}

// ByDrawCycleID orders the results by the draw_cycle_id field.
func ByDrawCycleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrawCycleID, opts...).ToFunc()
}

// ByDrawCycleIndex orders the results by the draw_cycle_index field.
func ByDrawCycleIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrawCycleIndex, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// ByDrawCycleField orders the results by draw_cycle field.
func ByDrawCycleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDrawCycleStep(), sql.OrderByField(field, opts...))
	}
}

// ByBalanceLedgerCount orders the results by balance_ledger count.
func ByBalanceLedgerCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBalanceLedgerStep(), opts...)
	}
}

// ByBalanceLedger orders the results by balance_ledger terms.
func ByBalanceLedger(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBalanceLedgerStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCardKeysCount orders the results by card_keys count.
func ByCardKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCardKeysStep(), opts...)
	}
}

// ByCardKeys orders the results by card_keys terms.
func ByCardKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newDrawCycleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DrawCycleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DrawCycleTable, DrawCycleColumn),
	)
}
func newBalanceLedgerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BalanceLedgerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BalanceLedgerTable, BalanceLedgerColumn),
	)
}
func newCardKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CardKeysTable, CardKeysColumn),
	)
}
