// Code generated by ent, DO NOT EDIT.

package shoporder

import (
	"ikik-api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldUserID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductID, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductName, v))
}

// ProductCoverURL applies equality check predicate on the "product_cover_url" field. It's identical to ProductCoverURLEQ.
func ProductCoverURL(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductCoverURL, v))
}

// ProductDescription applies equality check predicate on the "product_description" field. It's identical to ProductDescriptionEQ.
func ProductDescription(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductDescription, v))
}

// ProductType applies equality check predicate on the "product_type" field. It's identical to ProductTypeEQ.
func ProductType(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductType, v))
}

// UnitPrice applies equality check predicate on the "unit_price" field. It's identical to UnitPriceEQ.
func UnitPrice(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldUnitPrice, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldQuantity, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// PointsAmount applies equality check predicate on the "points_amount" field. It's identical to PointsAmountEQ.
func PointsAmount(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPointsAmount, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPaymentOrderID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldStatus, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPaidAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldCompletedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldCancelledAt, v))
}

// FailedReason applies equality check predicate on the "failed_reason" field. It's identical to FailedReasonEQ.
func FailedReason(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldFailedReason, v))
}

// DrawRewardAmount applies equality check predicate on the "draw_reward_amount" field. It's identical to DrawRewardAmountEQ.
func DrawRewardAmount(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldDrawRewardAmount, v))
}

// DrawCycleID applies equality check predicate on the "draw_cycle_id" field. It's identical to DrawCycleIDEQ.
func DrawCycleID(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldDrawCycleID, v))
}

// DrawCycleIndex applies equality check predicate on the "draw_cycle_index" field. It's identical to DrawCycleIndexEQ.
func DrawCycleIndex(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldDrawCycleIndex, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldProductName, v))
}

// ProductCoverURLEQ applies the EQ predicate on the "product_cover_url" field.
func ProductCoverURLEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductCoverURL, v))
}

// ProductCoverURLNEQ applies the NEQ predicate on the "product_cover_url" field.
func ProductCoverURLNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldProductCoverURL, v))
}

// ProductCoverURLIn applies the In predicate on the "product_cover_url" field.
func ProductCoverURLIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldProductCoverURL, vs...))
}

// ProductCoverURLNotIn applies the NotIn predicate on the "product_cover_url" field.
func ProductCoverURLNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldProductCoverURL, vs...))
}

// ProductCoverURLGT applies the GT predicate on the "product_cover_url" field.
func ProductCoverURLGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldProductCoverURL, v))
}

// ProductCoverURLGTE applies the GTE predicate on the "product_cover_url" field.
func ProductCoverURLGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldProductCoverURL, v))
}

// ProductCoverURLLT applies the LT predicate on the "product_cover_url" field.
func ProductCoverURLLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldProductCoverURL, v))
}

// ProductCoverURLLTE applies the LTE predicate on the "product_cover_url" field.
func ProductCoverURLLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldProductCoverURL, v))
}

// ProductCoverURLContains applies the Contains predicate on the "product_cover_url" field.
func ProductCoverURLContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldProductCoverURL, v))
}

// ProductCoverURLHasPrefix applies the HasPrefix predicate on the "product_cover_url" field.
func ProductCoverURLHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldProductCoverURL, v))
}

// ProductCoverURLHasSuffix applies the HasSuffix predicate on the "product_cover_url" field.
func ProductCoverURLHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldProductCoverURL, v))
}

// ProductCoverURLIsNil applies the IsNil predicate on the "product_cover_url" field.
func ProductCoverURLIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldProductCoverURL))
}

// ProductCoverURLNotNil applies the NotNil predicate on the "product_cover_url" field.
func ProductCoverURLNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldProductCoverURL))
}

// ProductCoverURLEqualFold applies the EqualFold predicate on the "product_cover_url" field.
func ProductCoverURLEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldProductCoverURL, v))
}

// ProductCoverURLContainsFold applies the ContainsFold predicate on the "product_cover_url" field.
func ProductCoverURLContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldProductCoverURL, v))
}

// ProductDescriptionEQ applies the EQ predicate on the "product_description" field.
func ProductDescriptionEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductDescription, v))
}

// ProductDescriptionNEQ applies the NEQ predicate on the "product_description" field.
func ProductDescriptionNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldProductDescription, v))
}

// ProductDescriptionIn applies the In predicate on the "product_description" field.
func ProductDescriptionIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldProductDescription, vs...))
}

// ProductDescriptionNotIn applies the NotIn predicate on the "product_description" field.
func ProductDescriptionNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldProductDescription, vs...))
}

// ProductDescriptionGT applies the GT predicate on the "product_description" field.
func ProductDescriptionGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldProductDescription, v))
}

// ProductDescriptionGTE applies the GTE predicate on the "product_description" field.
func ProductDescriptionGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldProductDescription, v))
}

// ProductDescriptionLT applies the LT predicate on the "product_description" field.
func ProductDescriptionLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldProductDescription, v))
}

// ProductDescriptionLTE applies the LTE predicate on the "product_description" field.
func ProductDescriptionLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldProductDescription, v))
}

// ProductDescriptionContains applies the Contains predicate on the "product_description" field.
func ProductDescriptionContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldProductDescription, v))
}

// ProductDescriptionHasPrefix applies the HasPrefix predicate on the "product_description" field.
func ProductDescriptionHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldProductDescription, v))
}

// ProductDescriptionHasSuffix applies the HasSuffix predicate on the "product_description" field.
func ProductDescriptionHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldProductDescription, v))
}

// ProductDescriptionIsNil applies the IsNil predicate on the "product_description" field.
func ProductDescriptionIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldProductDescription))
}

// ProductDescriptionNotNil applies the NotNil predicate on the "product_description" field.
func ProductDescriptionNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldProductDescription))
}

// ProductDescriptionEqualFold applies the EqualFold predicate on the "product_description" field.
func ProductDescriptionEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldProductDescription, v))
}

// ProductDescriptionContainsFold applies the ContainsFold predicate on the "product_description" field.
func ProductDescriptionContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldProductDescription, v))
}

// ProductTypeEQ applies the EQ predicate on the "product_type" field.
func ProductTypeEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldProductType, v))
}

// ProductTypeNEQ applies the NEQ predicate on the "product_type" field.
func ProductTypeNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldProductType, v))
}

// ProductTypeIn applies the In predicate on the "product_type" field.
func ProductTypeIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldProductType, vs...))
}

// ProductTypeNotIn applies the NotIn predicate on the "product_type" field.
func ProductTypeNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldProductType, vs...))
}

// ProductTypeGT applies the GT predicate on the "product_type" field.
func ProductTypeGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldProductType, v))
}

// ProductTypeGTE applies the GTE predicate on the "product_type" field.
func ProductTypeGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldProductType, v))
}

// ProductTypeLT applies the LT predicate on the "product_type" field.
func ProductTypeLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldProductType, v))
}

// ProductTypeLTE applies the LTE predicate on the "product_type" field.
func ProductTypeLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldProductType, v))
}

// ProductTypeContains applies the Contains predicate on the "product_type" field.
func ProductTypeContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldProductType, v))
}

// ProductTypeHasPrefix applies the HasPrefix predicate on the "product_type" field.
func ProductTypeHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldProductType, v))
}

// ProductTypeHasSuffix applies the HasSuffix predicate on the "product_type" field.
func ProductTypeHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldProductType, v))
}

// ProductTypeEqualFold applies the EqualFold predicate on the "product_type" field.
func ProductTypeEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldProductType, v))
}

// ProductTypeContainsFold applies the ContainsFold predicate on the "product_type" field.
func ProductTypeContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldProductType, v))
}

// UnitPriceEQ applies the EQ predicate on the "unit_price" field.
func UnitPriceEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldUnitPrice, v))
}

// UnitPriceNEQ applies the NEQ predicate on the "unit_price" field.
func UnitPriceNEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldUnitPrice, v))
}

// UnitPriceIn applies the In predicate on the "unit_price" field.
func UnitPriceIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldUnitPrice, vs...))
}

// UnitPriceNotIn applies the NotIn predicate on the "unit_price" field.
func UnitPriceNotIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldUnitPrice, vs...))
}

// UnitPriceGT applies the GT predicate on the "unit_price" field.
func UnitPriceGT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldUnitPrice, v))
}

// UnitPriceGTE applies the GTE predicate on the "unit_price" field.
func UnitPriceGTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldUnitPrice, v))
}

// UnitPriceLT applies the LT predicate on the "unit_price" field.
func UnitPriceLT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldUnitPrice, v))
}

// UnitPriceLTE applies the LTE predicate on the "unit_price" field.
func UnitPriceLTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldUnitPrice, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldQuantity, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldTotalAmount, v))
}

// PointsAmountEQ applies the EQ predicate on the "points_amount" field.
func PointsAmountEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPointsAmount, v))
}

// PointsAmountNEQ applies the NEQ predicate on the "points_amount" field.
func PointsAmountNEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldPointsAmount, v))
}

// PointsAmountIn applies the In predicate on the "points_amount" field.
func PointsAmountIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldPointsAmount, vs...))
}

// PointsAmountNotIn applies the NotIn predicate on the "points_amount" field.
func PointsAmountNotIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldPointsAmount, vs...))
}

// PointsAmountGT applies the GT predicate on the "points_amount" field.
func PointsAmountGT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldPointsAmount, v))
}

// PointsAmountGTE applies the GTE predicate on the "points_amount" field.
func PointsAmountGTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldPointsAmount, v))
}

// PointsAmountLT applies the LT predicate on the "points_amount" field.
func PointsAmountLT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldPointsAmount, v))
}

// PointsAmountLTE applies the LTE predicate on the "points_amount" field.
func PointsAmountLTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldPointsAmount, v))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDIsNil applies the IsNil predicate on the "payment_order_id" field.
func PaymentOrderIDIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldPaymentOrderID))
}

// PaymentOrderIDNotNil applies the NotNil predicate on the "payment_order_id" field.
func PaymentOrderIDNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldPaymentOrderID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldStatus, v))
}

// DeliveredCardsIsNil applies the IsNil predicate on the "delivered_cards" field.
func DeliveredCardsIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldDeliveredCards))
}

// DeliveredCardsNotNil applies the NotNil predicate on the "delivered_cards" field.
func DeliveredCardsNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldDeliveredCards))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldPaidAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldCompletedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldCancelledAt))
}

// FailedReasonEQ applies the EQ predicate on the "failed_reason" field.
func FailedReasonEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldFailedReason, v))
}

// FailedReasonNEQ applies the NEQ predicate on the "failed_reason" field.
func FailedReasonNEQ(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldFailedReason, v))
}

// FailedReasonIn applies the In predicate on the "failed_reason" field.
func FailedReasonIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldFailedReason, vs...))
}

// FailedReasonNotIn applies the NotIn predicate on the "failed_reason" field.
func FailedReasonNotIn(vs ...string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldFailedReason, vs...))
}

// FailedReasonGT applies the GT predicate on the "failed_reason" field.
func FailedReasonGT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldFailedReason, v))
}

// FailedReasonGTE applies the GTE predicate on the "failed_reason" field.
func FailedReasonGTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldFailedReason, v))
}

// FailedReasonLT applies the LT predicate on the "failed_reason" field.
func FailedReasonLT(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldFailedReason, v))
}

// FailedReasonLTE applies the LTE predicate on the "failed_reason" field.
func FailedReasonLTE(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldFailedReason, v))
}

// FailedReasonContains applies the Contains predicate on the "failed_reason" field.
func FailedReasonContains(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContains(FieldFailedReason, v))
}

// FailedReasonHasPrefix applies the HasPrefix predicate on the "failed_reason" field.
func FailedReasonHasPrefix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasPrefix(FieldFailedReason, v))
}

// FailedReasonHasSuffix applies the HasSuffix predicate on the "failed_reason" field.
func FailedReasonHasSuffix(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldHasSuffix(FieldFailedReason, v))
}

// FailedReasonIsNil applies the IsNil predicate on the "failed_reason" field.
func FailedReasonIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldFailedReason))
}

// FailedReasonNotNil applies the NotNil predicate on the "failed_reason" field.
func FailedReasonNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldFailedReason))
}

// FailedReasonEqualFold applies the EqualFold predicate on the "failed_reason" field.
func FailedReasonEqualFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEqualFold(FieldFailedReason, v))
}

// FailedReasonContainsFold applies the ContainsFold predicate on the "failed_reason" field.
func FailedReasonContainsFold(v string) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldContainsFold(FieldFailedReason, v))
}

// DrawRewardAmountEQ applies the EQ predicate on the "draw_reward_amount" field.
func DrawRewardAmountEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldDrawRewardAmount, v))
}

// DrawRewardAmountNEQ applies the NEQ predicate on the "draw_reward_amount" field.
func DrawRewardAmountNEQ(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldDrawRewardAmount, v))
}

// DrawRewardAmountIn applies the In predicate on the "draw_reward_amount" field.
func DrawRewardAmountIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldDrawRewardAmount, vs...))
}

// DrawRewardAmountNotIn applies the NotIn predicate on the "draw_reward_amount" field.
func DrawRewardAmountNotIn(vs ...float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldDrawRewardAmount, vs...))
}

// DrawRewardAmountGT applies the GT predicate on the "draw_reward_amount" field.
func DrawRewardAmountGT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldDrawRewardAmount, v))
}

// DrawRewardAmountGTE applies the GTE predicate on the "draw_reward_amount" field.
func DrawRewardAmountGTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldDrawRewardAmount, v))
}

// DrawRewardAmountLT applies the LT predicate on the "draw_reward_amount" field.
func DrawRewardAmountLT(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldDrawRewardAmount, v))
}

// DrawRewardAmountLTE applies the LTE predicate on the "draw_reward_amount" field.
func DrawRewardAmountLTE(v float64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldDrawRewardAmount, v))
}

// DrawRewardAmountIsNil applies the IsNil predicate on the "draw_reward_amount" field.
func DrawRewardAmountIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldDrawRewardAmount))
}

// DrawRewardAmountNotNil applies the NotNil predicate on the "draw_reward_amount" field.
func DrawRewardAmountNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldDrawRewardAmount))
}

// DrawCycleIDEQ applies the EQ predicate on the "draw_cycle_id" field.
func DrawCycleIDEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldDrawCycleID, v))
}

// DrawCycleIDNEQ applies the NEQ predicate on the "draw_cycle_id" field.
func DrawCycleIDNEQ(v int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldDrawCycleID, v))
}

// DrawCycleIDIn applies the In predicate on the "draw_cycle_id" field.
func DrawCycleIDIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldDrawCycleID, vs...))
}

// DrawCycleIDNotIn applies the NotIn predicate on the "draw_cycle_id" field.
func DrawCycleIDNotIn(vs ...int64) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldDrawCycleID, vs...))
}

// DrawCycleIDIsNil applies the IsNil predicate on the "draw_cycle_id" field.
func DrawCycleIDIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldDrawCycleID))
}

// DrawCycleIDNotNil applies the NotNil predicate on the "draw_cycle_id" field.
func DrawCycleIDNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldDrawCycleID))
}

// DrawCycleIndexEQ applies the EQ predicate on the "draw_cycle_index" field.
func DrawCycleIndexEQ(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldEQ(FieldDrawCycleIndex, v))
}

// DrawCycleIndexNEQ applies the NEQ predicate on the "draw_cycle_index" field.
func DrawCycleIndexNEQ(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNEQ(FieldDrawCycleIndex, v))
}

// DrawCycleIndexIn applies the In predicate on the "draw_cycle_index" field.
func DrawCycleIndexIn(vs ...int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIn(FieldDrawCycleIndex, vs...))
}

// DrawCycleIndexNotIn applies the NotIn predicate on the "draw_cycle_index" field.
func DrawCycleIndexNotIn(vs ...int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotIn(FieldDrawCycleIndex, vs...))
}

// DrawCycleIndexGT applies the GT predicate on the "draw_cycle_index" field.
func DrawCycleIndexGT(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGT(FieldDrawCycleIndex, v))
}

// DrawCycleIndexGTE applies the GTE predicate on the "draw_cycle_index" field.
func DrawCycleIndexGTE(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldGTE(FieldDrawCycleIndex, v))
}

// DrawCycleIndexLT applies the LT predicate on the "draw_cycle_index" field.
func DrawCycleIndexLT(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLT(FieldDrawCycleIndex, v))
}

// DrawCycleIndexLTE applies the LTE predicate on the "draw_cycle_index" field.
func DrawCycleIndexLTE(v int) predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldLTE(FieldDrawCycleIndex, v))
}

// DrawCycleIndexIsNil applies the IsNil predicate on the "draw_cycle_index" field.
func DrawCycleIndexIsNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldIsNull(FieldDrawCycleIndex))
}

// DrawCycleIndexNotNil applies the NotNil predicate on the "draw_cycle_index" field.
func DrawCycleIndexNotNil() predicate.ShopOrder {
	return predicate.ShopOrder(sql.FieldNotNull(FieldDrawCycleIndex))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.ShopProduct) predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDrawCycle applies the HasEdge predicate on the "draw_cycle" edge.
func HasDrawCycle() predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DrawCycleTable, DrawCycleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDrawCycleWith applies the HasEdge predicate on the "draw_cycle" edge with a given conditions (other predicates).
func HasDrawCycleWith(preds ...predicate.ShopDrawCycle) predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := newDrawCycleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBalanceLedger applies the HasEdge predicate on the "balance_ledger" edge.
func HasBalanceLedger() predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BalanceLedgerTable, BalanceLedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBalanceLedgerWith applies the HasEdge predicate on the "balance_ledger" edge with a given conditions (other predicates).
func HasBalanceLedgerWith(preds ...predicate.ShopBalanceLedger) predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := newBalanceLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCardKeys applies the HasEdge predicate on the "card_keys" edge.
func HasCardKeys() predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CardKeysTable, CardKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCardKeysWith applies the HasEdge predicate on the "card_keys" edge with a given conditions (other predicates).
func HasCardKeysWith(preds ...predicate.ShopCardKey) predicate.ShopOrder {
	return predicate.ShopOrder(func(s *sql.Selector) {
		step := newCardKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShopOrder) predicate.ShopOrder {
	return predicate.ShopOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShopOrder) predicate.ShopOrder {
	return predicate.ShopOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShopOrder) predicate.ShopOrder {
	return predicate.ShopOrder(sql.NotPredicates(p))
}
